### ISSUE TITLE
options 不传 intent 字段报错

### ISSUE THREAD

**Issue by gogoodboy** [suanmei/callapp-lib#10]
你好，谢谢你的开源，我从文档看到，	

> 实例化过程中，需要传递一个 options 对象给类，options 对象各属性需要严格按照下面的格式。
> 
> 下面所有不是必填的，如果你不需要传值，就不要写这个属性，而不是传递一个空字符串或者空对象，callapp-lib 并未对这种情况进行严格的检测。

恰好我有个 APP 只有 iOS 端，没有传到 intent 这个字段，在这个位置因为 intent 为 null 报错了，反馈一下，
也有可能我的例子比较特别，只有一个端。

function generateIntent(config, options) {
	  var outChain = options.outChain;
	  var intent = options.intent,
	      fallback = options.fallback;

> 	  var intentParam = _Object$keys(intent).map(function (key) {
> 	    return key + '=' + intent[key] + ';';
> 	  }).join('');

**Comment by suanmei** [comment]
1.7.2 已解决
