### ISSUE TITLE
ios系统scheme的方式调起app后会自动跳转到app store 是怎么回事

### ISSUE THREAD

**Issue by cuikaidao1992** [suanmei/callapp-lib#100]
+ 版本号: callapp-lib@
v3.0.0
+ 配置Option: 

``` json
 {
  "scheme": {},
  "outChain": {},
  "intent": {},
  "universal": {},
  "appstore": "",
  "yingyongbao": "",
  "fallback": ""
 }
```

+ 机型、系统、APP:
iPhone 6sp iPhone11
+ 遇到的问题及复现步骤:
H5页面调起app后，隔1s又跳转到app store了
+ 期望的效果:
调起app后留在app页就可以了

**Comment by chenshipi** [comment]
6sp 遇到过，引起问题的原因是因为默认的timeout是2秒，实际唤醒时间超过2秒，所以在app被唤醒后会跳到app store，你可以试试是不是这个问题

**Comment by tanglili** [comment]
我设置了超过2秒的时间，也会直接跳转到app store，不知道是什么问题，而且在safari里已经调用调试成功了

**Comment by suanmei** [comment]
已经有过同样的issue

常见问题汇总： https://www.yuque.com/egm961/nmf9nm/llbg79 ，参见第六个问题
