### ISSUE TITLE
百度贴吧与bilibili在安卓浏览器中未点击授权框 也不会跳转到下载页 的实现疑问

### ISSUE THREAD

**Issue by WuDiXiaoShuaiCai** [suanmei/callapp-lib#101]
+ 版本号: callapp-lib@

+ 配置Option: 

``` json
 {
  "scheme": {},
  "outChain": {},
  "intent": {},
  "universal": {},
  "appstore": "",
  "yingyongbao": "",
  "fallback": ""
 }
```

+ 机型、系统、APP:

+ 遇到的问题及复现步骤:
    浏览器唤起app时，如果未点击授权框，则会在指定延时之后跳转到下载页。但是我看到贴吧app等：在已安装app时，弹出授权框， 不点击确认，也不会跳转到下载页，而是留在当前页。 在没有安装app时，则直接跳转下载页。
+ 期望的效果:
请问大佬这种效果是怎样的实现方式呢

**Comment by suanmei** [comment]
但凡问问题多提供一些信息哈。你在安卓还是iOS上，在哪个浏览器中，通过你的描述我一概不知。

我猜测你是用的 iPhone，iPhone 的 universal-link 可以做到这些
