### ISSUE TITLE
Chrome浏览器唤醒异常，手机自带浏览器正常

### ISSUE THREAD

**Issue by dtcy1991** [suanmei/callapp-lib#102]
+ 版本号: callapp-lib@

+ 配置Option: 

``` json
{
        // 必填
        scheme: {
          protocol: 'shuzih',
          host: 'shuzih.com'
        },
        // outChain: {
        // 	protocol: 'commercial',
        // 	path: 'temporary',
        // 	key: 'url',
        // },
        intent: {
          //action: 'android.intent.action.VIEW',
          package: 'com.hlzt.commercial',
          scheme: 'shuzih',
        },
        //universal: {
        // 	host: 'www.shuzih.com/',
        // 	pathKey: 'action',
        //},
        appstore: 'https://itunes.apple.com/cn/app/id1241507162',       
        yingyongbao: '//a.app.qq.com/o/simple.jsp?pkgname=com.hlzt.commercial',
        fallback: 'http://cdn.shuzih.com/shuzih.apk',
        timeout: 2000,
      }
```

+ 机型、系统、APP:
vivo X7

+ 遇到的问题及复现步骤:
手机自带浏览器已安装唤醒app、未安装提示下载功能正常。手机Chrome浏览器内已安装的情况下无法唤醒成功，直接提示重新下载。
![image](https://user-images.githubusercontent.com/50286896/92589868-d12fa700-f2cd-11ea-831f-dc9432f04e5e.png)
一下为manifest配置的intent-filter
           <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="shuzih.com"
                    android:scheme="shuzih" />
            </intent-filter>
+ 期望的效果:
本人开发新手，劳驾大神们帮忙查明原因并解决

**Comment by suanmei** [comment]
你的自带浏览器可能是使用的scheme，chrome里用的是intent
