### ISSUE TITLE
iphone上无法调起淘宝

### ISSUE THREAD

**Issue by kexuebiao** [suanmei/callapp-lib#104]
+ 版本号: callapp-lib@3.1.3

+ 配置Option: 

``` json
 {  scheme: {
            protocol: 'taobao',
            host: 'detail.m.tmall.com/item.htm?id=616921659731',
          },
          appstore: 'https://itunes.apple.com/cn/app/id387682726',
          timeout: 5000,
        }
```
const callLib = new CallApp(option);
      callLib.open({ 
        path: '' 
      });

+ 机型、系统、APP:
iphone 6s  14.0.1 

+ 遇到的问题及复现步骤:
直接调用 window.open(`taobao://detail.m.tmall.com/item.htm?id=616921659731`);的化,可以在iphone 的safari 上调起淘宝,并且打开对应的页面,但 callLib.open 的化,不能调起淘宝

+ 期望的效果:
通过 callLib.open 调起淘宝

**Comment by suanmei** [comment]
朋友，你配置有问题。按如下配置

```
const option = {
  scheme: {
    protocol: 'taobao',
    host: 'detail.m.tmall.com',
  },
  appstore: 'https://itunes.apple.com/cn/app/id387682726',
  timeout: 5000,
  fallback: '',
};

const lib = new CallApp(option);

// 输出 - taobao://detail.m.tmall.com/item.htm?id=616921659731
console.log(lib.generateScheme({ path: 'item.htm', param: { id: 616921659731 } }));
```

**Comment by kexuebiao** [comment]
还是没有唤起淘宝

`const option = {
        scheme: {
          protocol: 'taobao',
          host: 'detail.tmall.com',
        },
        appstore: 'https://itunes.apple.com/cn/app/id387682726',
        timeout: 5000,
        fallback: '',
      };

      const lib = new CallApp(option);

      // 输出 - taobao://detail.m.tmall.com/item.htm?id=616921659731
      // console.log(lib.generateScheme({ path: 'item.htm', param: { id: 616921659731 } }));
      lib.open({path: 'item.htm', param: { id: 616921659731 }});`

**Comment by suanmei** [comment]
> 还是没有唤起淘宝
> 
> ```
> 
> const option = {
>         scheme: {
>           protocol: 'taobao',
>           host: 'detail.m.tmall.com',
>         },
>         appstore: 'https://itunes.apple.com/cn/app/id387682726',
>         timeout: 5000,
>         fallback: '',
>       };
> 
>       const lib = new CallApp(option);
> 
>       // 输出 - taobao://detail.m.tmall.com/item.htm?id=616921659731
>       // console.log(lib.generateScheme({ path: 'item.htm', param: { id: 616921659731 } }));
>       lib.open({path: 'item.htm', param: { id: 616921659731 }});
> ```

safari测试可以

**Comment by kexuebiao** [comment]
我的还是不行,
android手机可以唤醒,但ios的safari测试不行
有可能是ios14的问题吗

**Comment by kexuebiao** [comment]
应该是vux上使用的化,iphone无法唤醒 淘宝,楼主有什么办法吗
