### ISSUE TITLE
undefined is not a function (evaluating 'document.body.append(iframe)')

### ISSUE THREAD

**Issue by zhujunel** [suanmei/callapp-lib#108]
+ 版本号: callapp-lib@3.1.3

+ 配置Option: 

``` json
 {
  "scheme": {},
  "outChain": {},
  "intent": {},
  "universal": {},
  "appstore": "",
  "yingyongbao": "",
  "fallback": ""
 }
```

+ 机型、系统、APP:

+ 遇到的问题及复现步骤:
`TypeError：undefined is not a function (evaluating 'document.body.append(iframe)')`
没有尝试复现，目前是在Sentry平台上看到的
https://developer.mozilla.org/zh-CN/docs/Web/API/ParentNode/append#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9

+ 期望的效果:期望能改成`document.body.appendChild`

**Comment by suanmei** [comment]
你这个issue完全看不懂啊

**Comment by suanmei** [comment]
如何复现

**Comment by zhujunel** [comment]
> 如何复现

没有复现，是在我司的sentry平台上看到的。
