### ISSUE TITLE
问一下，在ios提示目标页面不存在，安卓直接不能唤起

### ISSUE THREAD

**Issue by dongweb** [suanmei/callapp-lib#11]
如题。ios下是可以唤起app的，提示目标页面不存在，这个怀疑是参数的拼接有问题吧，是否在程序里多加了斜杠之类的呢？
安卓没有办法唤起app，配置是按照你之前closed的一个issue做的。

**Comment by suanmei** [comment]
@dongweb universal Link 拼接是没有问题的。目标页面不存在的问题，这个需要让ios同学 debug 一下，定位问题，具体打开哪个页面的逻辑处理，是在他们那边的

安卓的问题你给到的信息太少了~~ 你可以问一下，安卓同学需要的scheme是什么样子的，然后和我这里的 generateScheme 返回的 scheme 进行一下对比

**Comment by dongweb** [comment]
> @dongweb universal Link 拼接是没有问题的。目标页面不存在的问题，这个需要让ios同学 debug 一下，定位问题，具体打开哪个页面的逻辑处理，是在他们那边的
> 
> 安卓的问题你给到的信息太少了~~ 你可以问一下，安卓同学需要的scheme是什么样子的，然后和我这里的 generateScheme 返回的 scheme 进行一下对比

非常感谢，现在ios已经没问题，是我配置的有问题
