### ISSUE TITLE
TypeError: document.body.append is not a function

### ISSUE THREAD

**Issue by BowenZ** [suanmei/callapp-lib#119]
+ npm 版本号: 
6.12.0
+ 配置 Option: 

``` js
const option = {
  scheme: {},
  outChain: {},
  intent: {},
  universal: {},
  appstore: '',
  yingyongbao: '',
  fallback: '',
};
```

+ 机型、系统、APP:
Android 6.0

+ 遇到的问题及复现步骤:
TypeError: document.body.append is not a function

+ 期望的效果:
如果插入的不是文本，建议方法替换为兼容性更好的 document.body.appendChild

**Comment by suanmei** [comment]
你安装的是最新版吗，master上分支就是append

**Comment by suanmei** [comment]
#108 之前解过 - https://github.com/suanmei/callapp-lib/commit/911c566b1846168604ce51db30f9cb609b5af181
 上个版本不小心换回去了
