### ISSUE TITLE
请问安卓的intent该如何实现能否给个详细的例子呢？

### ISSUE THREAD

**Issue by tombsmrliu** [suanmei/callapp-lib#12]
老哥，我用scheme方式发现安卓自带的浏览器唤醒一次可以，多次就不可以唤醒了，请问intent是否能解决呢？

**Comment by suanmei** [comment]
你的信息太少了，你是否 debug 了呢，第二次唤起的时候，是否执行到调用 scheme 那一行了；
然后， intent 实现你是想了解哪块，intent 唤端需要客户端支持 intent 唤起，然后问他们要相应的 intent 参数，按照文章里的格式拼一下就好了
