### ISSUE TITLE
ios中，未安装App的情况下，先弹出无法打开网页的提示，然后再提示跳转到AppStore

### ISSUE THREAD

**Issue by zgh0711** [suanmei/callapp-lib#14]
如题，callapp 版本1.7.3，在iOS手机上未安装要唤起的App的情况下，执行唤端操作后，先弹出无法打开网页的提示，关掉提示后才弹出去AppStore。
如果是安装了App的话则可以正常唤起，代码如下：
```
const CallApp = require('callapp-lib');
        const option = {
          protocol: 'youpeng',
          intent: {
            package: 'com.ypl.meetingsharec',
            scheme: 'youpeng',
          },
          // universal: {
          //   host: 'm1.youpenglai.com',
          //   pathKey: '',
          // },
          appstore: 'https://itunes.apple.com/cn/app/id1238992209',
          yingyongbao: 'http://a.app.qq.com/o/simple.jsp?pkgname=com.ypl.meetingshare',
          fallback: 'http://a.app.qq.com/o/simple.jsp?pkgname=com.ypl.meetingshare',
        };
        const callApp = new CallApp(option);
        callApp.open({
          path: ''
        });
```
截图如下：
![_20181217154924](https://user-images.githubusercontent.com/15401997/50073531-db656400-0213-11e9-8553-9c2a1a96f766.jpg)

**Comment by zgh0711** [comment]
![_20181217155753](https://user-images.githubusercontent.com/15401997/50073755-94c43980-0214-11e9-8b79-05f3bc30bbc0.png)
貌似是因为 AppStore 的 ID 后面多拼了个   :1  ,但是我的代码中并没有加这个  :1

**Comment by suanmei** [comment]
你截图的报错信息是你的文件缓存有问题。  
上面报地址无效，是 ios 中 scheme 唤起 app 的时候，如果 scheme 对应的 app 不存在，就会报错地址无法打开，我只能说试一下是否有办法避开

**Comment by zgh0711** [comment]
嗯，多谢了

**Comment by suanmei** [comment]
我发现 ios qq 现在已经无法通过 scheme 唤起 app 了，不知道安卓的是否也禁止了，简直是噩耗。你身边现在有安卓机吗，有的话能否帮忙验证一下安卓 qq 是否也禁止了。

你给某个按钮添加一个事件

```
window.top.location.href = 'your scheme'
```

看看能否唤起

**Comment by suanmei** [comment]
关于你的上面说的问题，我在文档里面其实有写

使用 URL Scheme 的弊端之一：

> 在 ios 上会有确认弹窗提示用户是否打开，对于用户来说唤端，多出了一步操作。若用户未安装 APP ，也会有一个提示窗，告知我们 “打不开该网页，因为网址无效”

目前没有办法避开这个

解决办法就是让你们的 ios 同学尽快支持 Universal Link 的实现😂

**Comment by zgh0711** [comment]
额，我没注意到这句话，那就只有用 Universal Link 来解决了

**Comment by usercao** [comment]
原来是这种问题🙏
