### ISSUE TITLE
大佬，微信浏览器唤醒app有开发标签唤醒了，考虑集成吗

### ISSUE THREAD

**Issue by Zeraswang** [suanmei/callapp-lib#140]
微信开发wx-open-launch-app标签，为用户提供在微信浏览器内部唤醒app
(https://developers.weixin.qq.com/doc/oplatform/Mobile_App/WeChat_H5_Launch_APP.html)

**Comment by suanmei** [comment]
你看最近的代码，已经在做支持中了
