### ISSUE TITLE
感谢分享，但是我尝试在自动唤起的时候就失败了，放在单击事件中却可以？

### ISSUE THREAD

**Issue by prohack** [suanmei/callapp-lib#15]
写了一个Vue项目，我在mounted()中直接唤起就会失败，但是如果在单击事件后调起则能够成功被唤起，请问有没有解决方法呢，项目中需要一进到页面就唤起..，谢谢了

**Comment by suanmei** [comment]
安卓和ios都这样吗

**Comment by prohack** [comment]
目前只测试了Android，在单击事件中是可以响应的，我贴下demo代码

**Comment by prohack** [comment]
![Uploading WeChat41be57a39d87be9277d843856ea5e04e.png…]()
这个showApp如果是通过组件的onclick触发的话，是可以正常调起的，但是如果我直接在mounted里面调用，或者模拟点击事件去调用都无效..

**Comment by prohack** [comment]
![image](https://user-images.githubusercontent.com/25928401/50584006-4af16b00-0e32-11e9-880c-cebeece86d51.png)
刚刚图片貌似没传上去，不好意思

**Comment by suanmei** [comment]
人尚在高铁上，到家了帮你看一下

**Comment by suanmei** [comment]
@prohack 嗨，回复晚了。url scheme 和 intent 在很多手机厂商以及很多浏览器中都不支持 js 直接触发，包括模拟点击，universal Link 是规定必须手动点击才可以触发。

不过 ios 中基本是可以实现直接通过 url scheme 来打开 APP 的

**Comment by suanmei** [comment]
@prohack 不知道你的一进入页面就唤起app的场景是什么？

1. 微信中调用 universal Link 会被拦截，所以在微信中需要一个中转页，中转页显示，点击右上角，然后选择在safari中打开，点击了后，直接就能唤起 app，这个是因为这个中转页 的 URI 本身就是 Universal Link

2. 普通的h5页面，一进入直接唤端，这个就只能通过 scheme 来实现了，ios 中 safari 是可以直接唤起 app 的，但是就像文章里写的一样，会有弹窗，询问 `是否在xx中打开`，安卓没测过

**Comment by prohack** [comment]
感谢回复～我们最后也是选择了点击打开的操作，等闲下来我研究下京东的唤起是怎么实现的，有结果的话希望能和你交流交流，这个库对对我很有帮助，再次感谢~
| |
carthach
|
|
邮箱：carthach@163.com
|

Signature is customized by Netease Mail Master

在2019年01月05日 21:06，拾邑 写道：

@prohack 嗨，回复晚了。url scheme 和 intent 在很多手机厂商以及很多浏览器中都不支持 js 直接触发，包括模拟点击，universal Link 是规定必须手动点击才可以触发。

不过 ios 中基本是可以实现直接通过 url scheme 来打开 APP 的

**Comment by qyjandroid** [comment]
> @prohack 京东哪个页面是可以直接唤起的，可以发一下链接我看一下😆期待你后面的研究成果，哈哈
下面是京东的链接，支持打开app。感觉京东兼容做的好一些。
https://3.cn/En7GOc?&utm_source=iosapp&utm_medium=appshare&utm_campaign=t_335139774&utm_term=CopyURL&ad_od=share&ShareTm=Q%2BBwX8%2B3oc7%2B3vPde5P4A98LT2yfdRpZXJ%2BiRcyrGaPFwii3aJgiYvpUCT5lZgwBJPH3LcDTKSRhOltF8uvZTWLPGi7/QgFx5UiKxjU3dNwQdML7rR2q37ZoAu8DO4ukTkzx/0yR0elGuTsHDO4efHf3/YtIjVR//wk4JW/b%2BsA=

**Comment by suanmei** [comment]
@qyjandroid 京东的这个，我试了一下几个机型，如下：
ios：
+ safari 中可以正常唤端，用的是 scheme ，你自己使用 scheme 也可以唤端
+ chrome 等浏览器中均不可以
+ 微信中可以，京东是腾讯干儿子，是在白名单里面的，可以调用微信的sdk，你们如果能加入白名单，你也可以在微信中打开即唤端

andriod（试了小米 MIX 以及 三星 MIX2）:
+ 无论是 chrome 还是 几家自带的浏览器都不可以
+ 微信中就不试了，肯定可以

最后，上结论，京东没做什么兼容，唯一的优势就是可以再微信中唤端，这个和技术无关，和血缘关系有关~

**Comment by miaoyuxinbaby** [comment]
@suanmei  您好，`京东是腾讯干儿子` 这句话逗乐我了。您真幽默，感谢。

**Comment by Bin851908788** [comment]
您好 请问这个问题有好的解决办法吗 我看拉钩教育是可以自动调起来的在小米浏览器下

**Comment by JaweenDeng** [comment]
页面上通过location.href="zhihu://"页面是不能自动触发的，我是加了一层服务端的重定向，进来页面还是location.href="/openApp",然后通过服务端，重定向到zhihu://，这样可以刷新页面自动调起知乎app

**Comment by suanmei** [comment]
> 页面上通过location.href="zhihu://"页面是不能自动触发的，我是加了一层服务端的重定向，进来页面还是location.href="/openApp",然后通过服务端，重定向到zhihu://，这样可以刷新页面自动调起知乎app

这个在所有的安卓手机中都好使吗，如果这中重定向的办法可行的话，我加到文档里

**Comment by JaweenDeng** [comment]
> > 页面上通过location.href="zhihu://"页面是不能自动触发的，我是加了一层服务端的重定向，进来页面还是location.href="/openApp",然后通过服务端，重定向到zhihu://，这样可以刷新页面自动调起知乎app
> 
> 这个在所有的安卓手机中都好使吗，如果这中重定向的办法可行的话，我加到文档里

我自己测试可以，安卓，iso上都可行，你可以测试一下

**Comment by huangmingfu** [comment]
“作者说：一般app，只有在ios safari中调用scheme唤端才可以实现进入页面自动唤起，其他场景均不可行。”
你们都是自动唤起失败？
我这边公司的app，安卓我测试了三星浏览器，uc浏览器，谷歌浏览器，系统自带的浏览器，都是可以页面挂载完毕就唤起app，都成功了，不过都是有那个询问弹窗。ios的话测试了Safari浏览器，也是有询问弹窗，自动唤起都没问题。
我这边两端用的都是URL Scheme，安卓的部分情况增加了Intent://的语法来唤起，大部分情况location.href = URL Scheme就行

**Comment by raohuiyong** [comment]
> “作者说：一般app，只有在ios safari中调用scheme唤端才可以实现进入页面自动唤起，其他场景均不可行。” 你们都是自动唤起失败？ 我这边公司的app，安卓我测试了三星浏览器，uc浏览器，谷歌浏览器，系统自带的浏览器，都是可以页面挂载完毕就唤起app，都成功了，不过都是有那个询问弹窗。ios的话测试了Safari浏览器，也是有询问弹窗，自动唤起都没问题。 我这边两端用的都是URL Scheme，安卓的部分情况增加了Intent://的语法来唤起，大部分情况location.href = URL Scheme就行

我就是小米手机自带的浏览器拉不起来，手动点击可以
