### ISSUE TITLE
求教，唤端失败，是参数的分析上出了问题吗？

### ISSUE THREAD

**Issue by melodyWxy** [suanmei/callapp-lib#16]
求解,     aliyun://forward/app?target_=/buy/renew  我想唤起这个页面。之前自己做了个唤端方法封装。但是小米与华为机型唤端失败。
想了想，看了您的博客，然后用了js自行触发的事件驱动，还是不行。
又看了您的作品，于是引了进来，根据文档的说明，我对此做出了解析，于是有了以下的代码。但两端都唤端失败。
代码如下，还是没明白解析上哪里出了问题。
```
const options = {
    scheme: {
        protocol:"aliyun://",
    },
    intent:{
      package:"com.alibaba.aliyun",
      scheme:"aliyun://",
    },
    fallback:"https://m.aliyun.com/product/ecs/renew#/"
};
const callLib = new CallApp(options);

callLib.open({
  param: {
     target_="/buy/renew"
  },
  path: 'forward/app'
});
```

**Comment by suanmei** [comment]
嗨，你好。应用宝和appstore地址也是必填的哈

**Comment by suanmei** [comment]
@melodyWxy 不好意思，是我这里版本发布因为 lock 文件出了问题，导致只能下载 1.7.3 版本，请下载最新 2.0.1 版本
