### ISSUE TITLE
你好，在微博和微信没办法唤起，是本来就不行还是我配置不对

### ISSUE THREAD

**Issue by linguoqiang001** [suanmei/callapp-lib#17]

**Comment by suanmei** [comment]
文章里有写，微博和微信，是需要想办法进他们的白名单才能唤端的，微信一般都是腾讯自家产品或者投资的产品可以进，微博的准入条件是，你们的app内嵌微博入口，能够三个月内引导用户打开超过 100w 次，就可以加入白名单了。

**Comment by suanmei** [comment]
@linguoqiang001 目前的 ReadME 针对的是 2.0.0 及以上版本，如果你的版本是 1.x.x 版本，记得升级一下哈~~

**Comment by yixinagqingyuan** [comment]
微博无法唤起为啥应用宝也跳转不了，麻烦指点一下，谢谢

**Comment by suanmei** [comment]
什么叫应用宝也跳转不了@yixinagqingyuan
