### ISSUE TITLE
测试小米手机自带浏览器打不开！

### ISSUE THREAD

**Issue by qyjandroid** [suanmei/callapp-lib#19]
测试小米手机自带浏览器打不开app

**Comment by suanmei** [comment]
![xxx](http://pleuhutbr.bkt.clouddn.com/Kapture%202019-01-16%20at%2013.50.36.gif)

**Comment by suanmei** [comment]
> http://pleuhutbr.bkt.clouddn.com/Kapture%202019-01-16%20at%2013.50.36.gif

查看这个gif吧，直接嵌入好像有点问题，小米自带浏览器没问题，你看看你是否有配置错误哈

**Comment by SmallWhirlwind** [comment]
我也发现小米自带浏览器打不开app，作者给的gif已经看不到了，能再发一次吗

**Comment by SmallWhirlwind** [comment]
你好，我拿到的是URL Scheme，小米自带浏览器现在有问题，我可以把URL Scheme变成intent吗？intent中的package: 我不知道填什么

**Comment by suanmei** [comment]
小米自带浏览器通过 intent 唤起，需要你升级一下 callapp-lib 的版本，这个功能是在 2.1.7 中才支持的。

URL 不可以变成 Intent，Intent唤端需要客户端同学开发相应的能力才可以支持

**Comment by SmallWhirlwind** [comment]
已经改用intent的方法，小米自带浏览器还是没能唤起。三星浏览器走同样的代码到intent的方式可以唤起。

**Comment by suanmei** [comment]
你的 intent 配置成功了是吗？我这边mi mix3前天试的是可以的

**Comment by SmallWhirlwind** [comment]
成功了，我用三星浏览器专门测了intent。我用的小米6

**Comment by SmallWhirlwind** [comment]
刚试了一下重启手机，发现重启以后，intent和tag a都可以唤起了，谢谢。你有过这种重启后成功的经历吗？我现在一头雾水不知道为什么成功的。

**Comment by suanmei** [comment]
有可能是缓存的原因哈
