### ISSUE TITLE
初始化总是失败

### ISSUE THREAD

**Issue by Fdango** [suanmei/callapp-lib#2]
// 这里对应到dist目录下面的index.cjs.js 
<script src="__JS__/index.cjs.js"></script>
<script>
    const options = {
        protocol: 'iOSJulyedu',
        appstore: "https://itunes.apple.com/cn/app/id1102275343?mt=8",
        yingyongbao: "//a.app.qq.com/o/simple.jsp?pkgname=com.youku.shortvideo",
        fallback: "https://dianliu.youku.com/service/advertise", // 这里暂时还是你们那个电流的地址
        logFunc: function() {
            console.log('11');
        }
    };
    const callLib = new CallApp(options);

    document.querySelector("#download").addEventListener("click",function(){
        callLib.open({
            path: 'redir1',
            param: {
                course: 100,
                video: 885
            },
            callback: function() {
                alert('失败')
            }
        });

    });
</script>

**Comment by suanmei** [comment]
cjs代表支持 commonjs 模块方式引入，是作为一个模块来用的哈
我晚上回去改成 umd 模式，你就可以直接<script> 调用了

**Comment by Fdango** [comment]
@suanmei 好的，因为我这边环境的原因，目前只能通过src形式进行引入，而且我发现电流那个项目微信当中并没有通过默认浏览器来进行，而是直接通过link唤起APP store了，是需求的原因么？

**Comment by Fdango** [comment]
@umd可以在给一个没有压缩过的么？

**Comment by suanmei** [comment]
@Fdango 目前已经支持 umd 啦，README 也已更新

**Comment by suanmei** [comment]
@Fdango 如果你想要未压缩版本的，可以把项目 clone 下来，将 `rollup.cinfig.js` 中的 `uglify(),` 这一行给去掉，运行一下 `npm run build`，这样编译出来的就是未压缩的了

**Comment by Fdango** [comment]
@suanmei 谢谢了
