### ISSUE TITLE
callapp-lib需要手动判断ios还是安卓，在进行配置吗？

### ISSUE THREAD

**Issue by LIAOTOW** [suanmei/callapp-lib#20]

**Comment by suanmei** [comment]
不需要手动判断，callapp-lib 内部都处理好了

**Comment by LIAOTOW** [comment]
scheme的protocol属性是填ios的标识还是安卓的标识

**Comment by suanmei** [comment]
这个应该是统一的呀

**Comment by Rong-CC** [comment]
为什么 scheme protocol 在ios百度浏览器上打不开

**Comment by suanmei** [comment]
@Rong-CC 因为百度也有白名单设置，你们如果有办法让百度把你们加到白名单中，才能正常唤端，微信同理

**Comment by suanmei** [comment]
@LIAOTOW 你们的ios开发在 [开发者中心](https://developer.apple.com/) 里的 Associated Domains 配置的域名是什么

**Comment by suanmei** [comment]
@LIAOTOW 你们的 ios 和 andriod 的 scheme 这块已经定下来开发完了没法改了吗，如果可以的话，尽量推动统一化

**Comment by LIAOTOW** [comment]
安卓那边改成短域名的Universal Link没有意义

**Comment by LIAOTOW** [comment]
域名配置就是 y02b.cn/g，因为要求直接点短信里的落地页链接直接进入app，不进入落地页，打不开事才进入落地页，所以  配置的就是短链接的域名

**Comment by LIAOTOW** [comment]
Universal Link ios已经可以打开了，但卸载了的话会跳到一个错误页面，不是说使用Universal Link的话不会跳转到错误的页面吗

**Comment by suanmei** [comment]
我在文档里有写，需要把你们的 universal Link 指向一个实际的页面，因为ios中调用universal Link ，苹果会先去检测域名是否有注册 universal Link，有注册的话，会尝试唤起app，唤起失败的话，会把它当做普通的 url 来处理，也就是打开这个地址

**Comment by suanmei** [comment]
Universal Link 是苹果家的功能，和 安卓没有关系。如果你们 安卓也想使用的话，可以让安卓支持一下 APP Link，它在安卓中的作用和 Universal Link 在 ios 中的作用等同

**Comment by 1zhizu** [comment]
ios那边用的scheme  也照着你的方法写了只是没有跟他配置参数  为什么点击苹果自带会说浏览器打不开页面  因为网址无效，应该怎么办呢   我用a 标签跳转就可以

**Comment by suanmei** [comment]
@1zhizu 贴一下失败和成功的代码

**Comment by 1zhizu** [comment]
失败的

**Comment by LIAOTOW** [comment]
产品改策略了  以后有时间在研究吧~.~

**Comment by 1zhizu** [comment]
callApp(){
      const options = {
        scheme:{
          ptotocol:'openeasydogapp://',
          host:''
        },
        intent:{
          package:'',
          scheme:'openeasydogapp://'
        },
        timeout: 2000,
        fallback:'https://itunes.apple.com/cn/app/id1437231713?mt=8',
      };
      const callLib = new CallApp(options);
        callLib.open({
          param:{},
          path:''
        });
    }    //失败的

<a href="openeasydogapp://" @click="callApp()" >打开App</a>       //成功的

**Comment by suanmei** [comment]
@LIAOTOW okay

**Comment by 1zhizu** [comment]
callApp(){
const options = {
scheme:{
ptotocol:'openXXX://',
host:''
},
intent:{
package:'',
scheme:'openXXX://'
},
timeout: 2000,
fallback:'https://xxx',
};
const callLib = new CallApp(options);
callLib.open({
param:{},
path:''
});
} //失败的

<a href="openXXX://" @click="callApp()" >打开App //成功的

**Comment by suanmei** [comment]
@1zhizu 打开页面立即唤端只有在 iso safari 中调用 scheme 才能成功，其他浏览器或者安卓系统均不可以。所以唤端功能最好放在某个按钮的点击事件中来实现

**Comment by 1zhizu** [comment]
是在 iso safari 中scheme链接失效调用的  但是就是点击苹果自带会说浏览器打不开页面 因为网址无效

**Comment by suanmei** [comment]
ios safari 中我前几天试着还是好的哈

**Comment by suanmei** [comment]
@1zhizu 你的邮箱甩一下

**Comment by suanmei** [comment]
```
import CallappLib from 'callapp-lib';

const option = {
  scheme: {
    protocol: 'ykshortvideo',
  },
  outChain: {
    protocol: 'ykshortvideo',
    path: 'temporary',
    key: 'url',
  },
  appstore: 'https://itunes.apple.com/cn/app/id1383186862',
  yingyongbao: '//a.app.qq.com/o/simple.jsp?pkgname=com.youku.shortvideo',
  fallback: 'https://dianliu.youku.com/service/download',
  timeout: 2000,
};
const lib = new CallappLib(option);

export default {
  name: 'home',
  mounted() {
    lib.open({
      path: 'home',
    });
  },
};
```
