### ISSUE TITLE
使用intent拉起时 浏览器询问触发失败页面

### ISSUE THREAD

**Issue by Hilbertangers** [suanmei/callapp-lib#23]
大部分安卓浏览器第一次拉起时都会询问用户是否打开，用户未确认前，就会跳转到fallback页面去，
第二次以后就不会了，请问有什么方案吗

**Comment by suanmei** [comment]
intent 是不会询问的，确认一下你的是 intent 还是 scheme 唤起

**Comment by suanmei** [comment]
没办法阻塞，把 timeout 设置成 3000 吧，因为检测页面唤端成功的方法就是，看你设置的 timeout 时间内，页面是否被隐藏（唤端成功，页面进入后台即隐藏），如果时间过长的话，万一真的唤端失败，会在当前页面停留太久。停留太短，会导致没有来得及点击唤端，就跳转到了预设的失败页面。

你取一个你认为合适的值就可以了

**Comment by Hilbertangers** [comment]
好吧 谢谢🙏
