### ISSUE TITLE
iOS 微信唤起的问题

### ISSUE THREAD

**Issue by draculapile** [suanmei/callapp-lib#24]
环境：iOS 12.0
机型：iPhone X，iphone 6s plus
问题：手机上装了测试版的app，app已配置 universal link，微信浏览器打开H5页面，iPhone X 会提示“即将离开微信，在App Store中打开”，6sp不会提示，再去Safari打开都可以成功唤起app，我看到源码中检测到微信环境，会传入应用的App Store地址，我把这部分改成
`if (browser.isWechat) {
        return;
      }`
还是会弹这个提示，是为什么呢？

**Comment by suanmei** [comment]
发一下代码

**Comment by draculapile** [comment]
![image](https://user-images.githubusercontent.com/24435036/53233612-c3550980-36c8-11e9-8f9e-1073875c2776.png)
![image](https://user-images.githubusercontent.com/24435036/53233673-ec759a00-36c8-11e9-8877-3f4fbd1b1809.png)

**Comment by suanmei** [comment]
@draculapile 代码没有问题，微信中没法调试，建议在关键节点alert，看代码实际怎么运行的

**Comment by draculapile** [comment]
> @draculapile 代码没有问题，微信中没法调试，建议在关键节点alert，看代码实际怎么运行的

好的，谢谢

**Comment by draculapile** [comment]
我把那几个 js 在本地引入，改了一下，问题解决了
