### ISSUE TITLE
大佬，这行代码请教一下

### ISSUE THREAD

**Issue by draculapile** [suanmei/callapp-lib#25]
https://github.com/suanmei/callapp-lib/blob/3f15dee805cb9f670cc98e21325b84b4aab2943e/index.js#L113
手机未安装app（app已配置 universal link）的情况下，debug 了一下代码是走到这一行了，我在 options 里配置了 universal 参数，所以会生成一个 link ，但是就停在跳转到的这个 link 页面，不会跳到app store 下载页面，按道理来说这里是会跳到 app store 吧，因为跳转的这个行为是苹果系统完成的？或者说这行代码下面增加一行 checkOpenFall = this.fallToAppStore 失败的处理？或者是我们 app 的 universal link 在服务端的配置有问题

**Comment by suanmei** [comment]
是这样的，universalLink 的处理逻辑是如果这个链接发现是可以唤起app的（在苹果开发者中心配置了并且手机上安装了app），则唤起app，如果不可以，则把universalLink地址当做一个页面url来打开

**Comment by draculapile** [comment]
> 是这样的，universalLink 的处理逻辑是如果这个链接发现是可以唤起app的（在苹果开发者中心配置了并且手机上安装了app），则唤起app，如果不可以，则把universalLink地址当做一个页面url来打开

ok，那我在下面加了 checkOpenFall = this.fallToAppStore 这行应该是可行的吧

**Comment by suanmei** [comment]
不行的，跳转开始了之后，eventLoop中的事件（setTimeout里的回调函数）就没机会执行了

**Comment by draculapile** [comment]
> 不行的，跳转开始了之后，eventLoop中的事件（setTimeout里的回调函数）就没机会执行了

"如果不可以，则把universalLink地址当做一个页面url来打开"，就是看 generateUniversalLink() 的返回值是不是能唤起 app 对吧，这里面做的拼接 URL格式 ，要跟 iOS 的同学协定好，是这个意思嘛

**Comment by suanmei** [comment]
是的，这个属于联调工作，但是一定要给 universalLink 指定一个页面，因为 universalLink本身就是一个 url，用户不一定安装了app，所以一定要让universalLink在无法唤起app的情况下，打开它对应的页面

**Comment by draculapile** [comment]
> 给 universalLink 指定一个页面

就是 https://域名/xx.html 这种引导下载页或者别的能正常浏览的web页面是么，这个配置是web这边来配？在哪里写啊

**Comment by suanmei** [comment]
你们可以直接扔一个页面到服务器对应的目录下，或者做一个重定向

**Comment by draculapile** [comment]
> 你们可以直接扔一个页面到服务器对应的目录下，或者做一个重定向

ok 十分感谢
