### ISSUE TITLE
关于ios在safari浏览器唤起应用的问题

### ISSUE THREAD

**Issue by hopperhuang** [suanmei/callapp-lib#27]
应用已经被成功唤起。从应用回退浏览器时，还是跳进了fallback的地址。
ios里面，visibilityChangeProperty 和 hidden回调的触发时机，总是要比timer慢，导致了这个问题的发生。
safari浏览器的行为好像是，timer会按时触发，而visibilityChangeProperty 和 hidden事件的回调，好像是，从app返回浏览器才监听到，然后触发，而不是离开safari浏览器就触发了。
所以导致清除timer的行为要在timer触发之后。

**Comment by DocBug** [comment]
safari 会一直弹出是否进入应用的框，如果我不选择的话，就会一直刷新。。这个怎么破

**Comment by suanmei** [comment]
你们的问题我目前没有遇到过，建议先debug追踪一下，是否是特殊机子下偶然触发的bug

**Comment by hopperhuang** [comment]
> 你们的问题我目前没有遇到过，建议先debug追踪一下，是否是特殊机子下偶然触发的bug
> 
> 希望你们能多留一些信息~

遇到问题的系统：ios 10 和 ios 11

**Comment by suanmei** [comment]
@hopperhuang @DocBug 嗨，不知道你们的问题解决了没有，我这里验证了没出现你们的情况

**Comment by hopperhuang** [comment]
@suanmei  你好，我的问题并没有解决。我最近也没有在研究这个问题。给不了你太多的帮助，难道是手机型号的问题？？或者safari浏览器版本的问题？
