### ISSUE TITLE
Chrome for Android浏览器打不开scheme连接

### ISSUE THREAD

**Issue by netfoxor** [suanmei/callapp-lib#28]
Chrome for Android没有设置Intent的情况下无效，跟代码发现无法通过iframe.src调用schema，本地测试通过a.href的方式可以成功调用，能否对chrome单独处理一下？

参考另一个库的研究过程（H5CallUpNative，不支持Universal links）
https://github.com/AlanZhang001/H5CallUpNative

**Comment by suanmei** [comment]
嗯，可以兼容。这块之前没做特殊处理，是因为我们这边都有实现 intent 功能。

然后你发的链接，不用参考。我的文章里面有写，可以参照第一个 issue。他的有些内容就是从我文章里拿的，对比一下就知道了

**Comment by suanmei** [comment]
3abdc3d17788d3b9b0c898004cdf4b537fa7e65a  已修复，感谢你的评论，还有问题欢迎直接提PR哈
