### ISSUE TITLE
如果ios和android的Scheme不一样可以用一个实例么？

### ISSUE THREAD

**Issue by shangxinbo** [suanmei/callapp-lib#29]
我理解这个库的编写者假定的是android app和ios app是同一个Scheme。
当然我觉得也该这样，但是我们的android组和ios组搞得就是两个schema，这样的话appstore的地址是不是应该在open参数里而不在实例初始化参数里，总感觉参数分布很别扭

**Comment by suanmei** [comment]
appstore 只是错误ios微信中无法唤端情况下的一个妥协，这是一个全局性的行为，为什么要在每次调用open函数的时候携带呢

**Comment by suanmei** [comment]
你可以利用 buildScheme 函数来自定义在安卓和ios中组成不同的 scheme
