### ISSUE TITLE
在微信端唤醒到应用宝无法跳转具体详情页

### ISSUE THREAD

**Issue by beicheng112** [suanmei/callapp-lib#31]
在微信中唤醒app ios可以跳转详情页 安卓无法跳转到详情页

**Comment by suanmei** [comment]
我代码里的逻辑，微信 ios 是直接跳转 appstore，怎么会跳转到详情页呢。。。

另：你可以debug一下代码，callapp-lib默认引用的main文件是没有压缩的，你可以把代码执行到哪一行，截个图

**Comment by suanmei** [comment]
> 刚刚我们说到，如果你不是微信的家属，那你是很难进入白名单的，所以在安卓中我们一般都是直接打开腾讯应用宝，ios 中 直接打开 App Store。点击腾讯应用宝中的“打开”按钮，可以直接唤起我们的 APP，但是无法打开 APP 中的某个功能（就是无法打开指定页面）。
腾讯应用宝对外开放了一个叫做 APP Link 的申请，只要你申请了 APP Link，就可以通过在打开应用宝的时候在应用宝地址后面添加上 &android_schema={your_scheme} ，来打开指定的页面了。

我在文档里面写过，应用宝打开指定页面的能力需要申请应用宝的APP Link

**Comment by beicheng112** [comment]
谢谢你，没看到，已经可以拉，配合移动端
