### ISSUE TITLE
手机 Chrome 浏览器无法唤起应用

### ISSUE THREAD

**Issue by maoweipeng** [suanmei/callapp-lib#32]
Android Chrome 72.0.3626.105
iOS Chrome 73.0.3683.68

按照文档填了 intent，手机 Chrome 浏览器还是无法唤起应用

**Comment by suanmei** [comment]
首先需要确认你们的安卓客户端是否支持 intent ，支持的话，找安卓同学联调一下，唤端的事情，主要还是让客户端来 debug。

另：intent 只支持 chrome for andriod

**Comment by maoweipeng** [comment]
客户端支持 intent ，Chrome 没有弹窗提示跳转，Safari 有弹窗提示跳转

**Comment by suanmei** [comment]
是这样哈，我也不知道你们大家是怎么配置的，具体也不好判断。首先 ios 和 intent 无关，safari 更没有关系，intent 只在安卓 chrome 原生 上起作用。

intent 唤起 app 本身就是没有弹窗的。callapp-lib 只是做一个 intent 的拼接，格式是遵循官方文档的规范。

如果你说我这块无法唤起 app ，只有这么几种情况，1. 我这块拼错了 2. 我对 chrome 的 ua 判断错误 3. 你配置出错了 4. 你们的客户端不支持

其实也好验证，既然你说你们的客户端支持 intent，肯定是你们的客户端已经自测好了，你问他们要一个能够唤起app的 intent 链接，然后根据那个 intent 去配置，对比一下我的库拼接出来的 intent。如果说不一致，你把你的 intent 链接 和 你的配置信息拿出来，我才好帮你解决问题。

什么信息不给，我真的没法去猜问题

**Comment by suanmei** [comment]
@maoweipeng 验证出来了吗
