### ISSUE TITLE
兼容UC浏览器

### ISSUE THREAD

**Issue by chneyu1105811473** [suanmei/callapp-lib#33]
目前的版本在UC浏览器中，在未安装app情况下貌似没有效果，在安装了app的情况下可以跳转。楼主是否有遇到这种问题呢

**Comment by suanmei** [comment]
未安装app，uc浏览器无效，不是很明白，具体是什么表现

**Comment by chneyu1105811473** [comment]
> 未安装app，uc浏览器无效，不是很明白，具体是什么表现

没有安装app的话，默认的失败回调没执行（我没有自定义失败回调，QQ，Chrome，safari能执行默认的失败回调）

**Comment by chneyu1105811473** [comment]
微博内置浏览器貌似也不OK呢，其他app的内置浏览器暂时还没有调试到~

**Comment by suanmei** [comment]
你是安卓还是ios，还有你的配置贴出来

**Comment by suanmei** [comment]
> 微博内置浏览器貌似也不OK呢，其他app的内置浏览器暂时还没有调试到~

微信也不okay，又是什么意思，微信要么是调用应用宝。要么是打开app store。有什么不ok的😂

**Comment by chneyu1105811473** [comment]
> > 微博内置浏览器貌似也不OK呢，其他app的内置浏览器暂时还没有调试到~
> 
> 微信也不okay，又是什么意思，微信要么是调用应用宝。要么是打开app store。有什么不ok的😂

不是微信不OK,是微博啦

**Comment by suanmei** [comment]
你把我上一个回复看一下

**Comment by chneyu1105811473** [comment]
> 你是安卓还是ios，还有你的配置贴出来

目前只哟ios版本的，配置如下：

1.options配置：
`options : {
        scheme: {
          protocol: 'xplo://'
        },
        appstore: 'https://itunes.apple.com/cn/app/id1449233544?mt=8',
        timeout: 500,
        fallback: 'http://www.xploers.com'
    }`

2.调用
      ` this.callLib = new CallApp(this.options)

        if (this.$store.state.deviceType.indexOf('ios')>-1) {
          const params = {
            id: this.$route.params.id
          }
          this.callLib.open({
            param: params,
            path: 'post'
          })
        } else if (this.$store.state.deviceType.indexOf('android')>-1) {
          this.dialog.isAndroid = true // 如果是安卓系统，弹出不支持安卓设备dialog
        }`

**Comment by suanmei** [comment]
你可以把  protocol 的`://`先去掉

**Comment by chneyu1105811473** [comment]
> 你可以把 protocol 的`://`先去掉

哈哈，刚才ios那边联调也发现这个问题了，已经去掉了

**Comment by suanmei** [comment]
@chneyu1105811473 你的问题解决了吗

**Comment by chneyu1105811473** [comment]
> @chneyu1105811473 你的问题解决了吗

目前UC可以跳转appstore，不过我现在只是使用了scheme的方式进行跳转，如果下载了app会弹出两次弹框（一次是进入appstore的弹框，一次是进app的弹框），感觉交互不是很友好，不知道同时使用universal link是不是就可以解决这个问题，还在优化当中……

**Comment by suanmei** [comment]
UC跳转app store 的逻辑是你在callapp-lib之外加的吗

使用Universal Link 这些问题确实就都可以一劳永逸得解决了

**Comment by chneyu1105811473** [comment]
> UC跳转app store 的逻辑是你在callapp-lib之外加的吗
> 
> 使用Universal Link 这些问题确实就都可以一劳永逸得解决了

我没有额外配置，最近莫名其妙可以了，囧！
我又个疑问，universal对象中的参数配置我不太理解，例如我把host直接写成我的根域名（如：https://www.xploers.com），pathKey不配置，然后在使用open函数调用的时候，例如
        const params = {
          id: this.$route.params.id
        }
        this.callLib.open({
          param: params,
          path: 'tour'
        })
是否也可以

**Comment by suanmei** [comment]
pathKey 是必需要填的，因为 `pathKey` 是客户端同学用来从url地址上获取 path 的key， `pathKey` 是 key, `path` 是 value，最后生成的地址类似于 host://pathKey=path&key2=value2

key2、value2 就是从 `open` 方法中的 param 里取的
