### ISSUE TITLE
没看明白怎么用

### ISSUE THREAD

**Issue by yuhaiyang1** [suanmei/callapp-lib#34]
比如我有个 我现在 depot://sxc.depot 怎么写代码呢？
a 链接和 iframe 和 location都可以用，但是不能在钉钉自带的浏览器里面用。
另外建议写个 example 的🌰

**Comment by suanmei** [comment]
嗨，感谢提出的建议。明天出example，以及对应的 scheme 或者 universalLink 如何配置

> a 链接和 iframe 和 location都可以用，但是不能在钉钉自带的浏览器里面用

不知道你说的是哪个不能用

**Comment by yuhaiyang1** [comment]
是三种方式 android 钉钉自带的浏览器都不能用，其他 qq浏览器、谷歌浏览器、uc 啊都不行。iOS 的钉钉任意方式是 ok 的
想试下这个包，但是没看明白怎么用。

**Comment by suanmei** [comment]
你说的不可用是你实验过吗。。。。我这里十几台测试机验证过，基本没问题。

Example得等明天啦😁

**Comment by yuhaiyang1** [comment]
对局域网node 起服务试过了，安卓的除了钉钉以外都可以，ios 全部可以。
然后像我 这个链接depot://sxc.depot ， npm i 以后不知道写法，入参什么的

**Comment by toored2** [comment]
遇到了QQ浏览器唤端失败的情况，坐等🌰，大佬加油

**Comment by suanmei** [comment]
已更新 example   @yuhaiyang1 @toored2
