### ISSUE TITLE
QQ 禁了Universal Link之后, 已下载app的, callapp-lib直接跳转appStore了

### ISSUE THREAD

**Issue by Kuohao-wu** [suanmei/callapp-lib#35]
QQ 禁了Universal Link之后, 已下载app的, callapp-lib直接跳转appStore了, 这样就不能直接打开某个app页面了吧. callapp-lib有没有针对ios QQ浏览器的配置, 打开一个引导从Safari打开的页面, 这样就能继续使用Universal Link了

**Comment by Kuohao-wu** [comment]
看了一下源码, 目前是判断QQ浏览器或者微信, 就自动跳转到appStore了.

**Comment by suanmei** [comment]
ios QQ浏览器也已经不支持 universal Link 了

**Comment by Kuohao-wu** [comment]
那大佬有什么解决方案吗? 现在我是判断 ios 端的QQ,然后打开引导页, 引导用户使用Safari打开, 但是又发现, universal link需要用户手动触发才能正确唤起, 不然唤端失败.

**Comment by suanmei** [comment]
我现在准备把 QQ 浏览器也换成自动调起 app store了，企鹅家越来越丧心病狂了，回头还得测一下微信端现在如何了。

引导用户使用 safari 打开，需要你本身的这个引导页的 URL 地址就是一个 universal Link，右上角三个点的`在safari中打开`，就算是手动触发。具体可见universal Link的官方文档

**Comment by Kuohao-wu** [comment]
好的, 谢谢dalao指点

**Comment by suanmei** [comment]
还有其他问题吗~
