### ISSUE TITLE
你好，现在还在维护吗？

### ISSUE THREAD

**Issue by coderMi** [suanmei/callapp-lib#36]
今天我们使用这个库的时候，碰到了一些问题。按照文档写好之后，不管是iOS端还是android端，都调起失败。

```
var options = {
        scheme: {
          protocol: 'szzx'
        },
        intent: {
          package: 'com.menglan.zhihu',
          scheme: 'szzx'
        },
        appstore: 'https://itunes.apple.com/cn/app/id1449703627?mt=8',
        yingyongbao: 'https://a.app.qq.com/o/simple.jsp?pkgname=com.menglan.zhihu',
        fallback: 'https://www.baidu.com'
      }
      var callLib = new CallApp(options)
      callLib.open({
        param: {questionId:para},
        path: ''
      })
```
这是我们的代码，能帮我看一下是哪里出问题了吗

**Comment by suanmei** [comment]
首先确认一下，你的 scheme 和 intent URL 是和客户端同学已经调试通过了，可以正常唤端的吗？

目前的 option 配置是正确的

**Comment by coderMi** [comment]
是可以的，接口其实已经配好了的。我们本来已经完成这个功能了，后来发现，华为默认浏览器和uc浏览器都掉不起来，因此想找一些资料，碰巧看到你在掘金的文章，因此就来试一试。结果发现，ios和华为qq浏览器，本来可以调起app的，现在都不行了------------------ 原始邮件 ------------------发件人: 拾邑  <notifications@github.com>发送时间: 2019年4月30日 20:11收件人: suanmei/callapp-lib <callapp-lib@noreply.github.com>抄送: coderMi <yuhf009@sina.com>, Author <author@noreply.github.com>主题: 回复：[suanmei/callapp-lib] 你好，现在还在维护吗？ (#36)首先确认一下，你的 scheme 和 intent URL 是和客户端同学已经调试通过了，可以正常唤端的吗？
目前的 option 配置是正确的

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/suanmei/callapp-lib","title":"suanmei/callapp-lib","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/suanmei/callapp-lib"}},"updates":{"snippets":[{"icon":"PERSON","message":"@suanmei in #36: 首先确认一下，你的 scheme 和 intent URL 是和客户端同学已经调试通过了，可以正常唤端的吗？\r\n\r\n目前的 option 配置是正确的"}],"action":{"name":"View Issue","url":"https://github.com/suanmei/callapp-lib/issues/36#issuecomment-487927638"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/suanmei/callapp-lib/issues/36#issuecomment-487927638",
"url": "https://github.com/suanmei/callapp-lib/issues/36#issuecomment-487927638",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by coderMi** [comment]
感谢回复，本来只是碰下运气的。------------------ 原始邮件 ------------------发件人: 拾邑  <notifications@github.com>发送时间: 2019年4月30日 20:11收件人: suanmei/callapp-lib <callapp-lib@noreply.github.com>抄送: coderMi <yuhf009@sina.com>, Author <author@noreply.github.com>主题: 回复：[suanmei/callapp-lib] 你好，现在还在维护吗？ (#36)首先确认一下，你的 scheme 和 intent URL 是和客户端同学已经调试通过了，可以正常唤端的吗？
目前的 option 配置是正确的

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/suanmei/callapp-lib","title":"suanmei/callapp-lib","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/suanmei/callapp-lib"}},"updates":{"snippets":[{"icon":"PERSON","message":"@suanmei in #36: 首先确认一下，你的 scheme 和 intent URL 是和客户端同学已经调试通过了，可以正常唤端的吗？\r\n\r\n目前的 option 配置是正确的"}],"action":{"name":"View Issue","url":"https://github.com/suanmei/callapp-lib/issues/36#issuecomment-487927638"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/suanmei/callapp-lib/issues/36#issuecomment-487927638",
"url": "https://github.com/suanmei/callapp-lib/issues/36#issuecomment-487927638",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by suanmei** [comment]
ios qq 浏览器本身已经把 scheme 给禁止掉了，不知道你们是怎么测试成功的，我刚才下载了你们的 app，用了你的配置，在 ios safari 中是可以正确唤端的。

**Comment by coderMi** [comment]
因为在ios端微信调用的是默认浏览器啊，所以并没有针对qq浏览器做适配。另外，您的意思是必须要先在所有的浏览器中调端成功，之后用您的插件才可以吗------------------ 原始邮件 ------------------发件人: 拾邑  <notifications@github.com>发送时间: 2019年5月1日 01:24收件人: suanmei/callapp-lib <callapp-lib@noreply.github.com>抄送: coderMi <yuhf009@sina.com>, Author <author@noreply.github.com>主题: 回复：[suanmei/callapp-lib] 你好，现在还在维护吗？ (#36)ios qq 浏览器本身已经把 scheme 给禁止掉了，不知道你们是怎么测试成功的，我刚才下载了你们的 app，用了你的配置，在 ios safari 中是可以正确唤端的。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/suanmei/callapp-lib","title":"suanmei/callapp-lib","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/suanmei/callapp-lib"}},"updates":{"snippets":[{"icon":"PERSON","message":"@suanmei in #36: ios qq 浏览器本身已经把 scheme 给禁止掉了，不知道你们是怎么测试成功的，我刚才下载了你们的 app，用了你的配置，在 ios safari 中是可以正确唤端的。\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/suanmei/callapp-lib/issues/36#issuecomment-488040539"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/suanmei/callapp-lib/issues/36#issuecomment-488040539",
"url": "https://github.com/suanmei/callapp-lib/issues/36#issuecomment-488040539",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by suanmei** [comment]
我只是针对你说的，你说ios端和安卓端都失败，我用safari试了下，就是可以的。

微信不管在ios上还是安卓都是不可以唤起app的，他们家有白名单机制，额，你把文章再看一遍吧，我都写过了

**Comment by suanmei** [comment]
你不可能在所有浏览器都调试成功的，很多浏览器比如百度都是有白名单机制的，这不是技术能解决的

**Comment by coderMi** [comment]
不是，因为所有的都调用失败，所以我们就换回以前的方法了------------------ 原始邮件 ------------------发件人: 拾邑  <notifications@github.com>发送时间: 2019年5月1日 11:47收件人: suanmei/callapp-lib <callapp-lib@noreply.github.com>抄送: coderMi <yuhf009@sina.com>, Author <author@noreply.github.com>主题: 回复：[suanmei/callapp-lib] 你好，现在还在维护吗？ (#36)我只是针对你说的，你说ios端和安卓端都失败，我用safari试了下，就是可以的。
微信不管在ios上还是安卓都是不可以唤起app的，他们家有白名单机制，额，你把文章再看一遍吧，我都写过了

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/suanmei/callapp-lib","title":"suanmei/callapp-lib","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/suanmei/callapp-lib"}},"updates":{"snippets":[{"icon":"PERSON","message":"@suanmei in #36: 我只是针对你说的，你说ios端和安卓端都失败，我用safari试了下，就是可以的。\n\n微信不管在ios上还是安卓都是不可以唤起app的，他们家有白名单机制，额，你把文章再看一遍吧，我都写过了"}],"action":{"name":"View Issue","url":"https://github.com/suanmei/callapp-lib/issues/36#issuecomment-488204764"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/suanmei/callapp-lib/issues/36#issuecomment-488204764",
"url": "https://github.com/suanmei/callapp-lib/issues/36#issuecomment-488204764",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by suanmei** [comment]
不知道你是怎么个情况，我用你的配置，下载你们的app都唤起了

**Comment by SilentFlute** [comment]
@coderMi 你好，我用这个库已经快3个月，有些时候唤起不完美，不过总体来说还不错，这是我的配置
```
export const handleCallApp = (path = "", param = null) => {
    let openObj = param
            ? {
                path,
                param
            }
            : {
                path
            },
        callBackUrl = "ios就是app store地址，安卓就是应用宝地址",
        options = {
            scheme:{
                protocol:"url scheme的scheme字段",
                host:"url scheme的host字段"
            },
            intent:{
                package:"安卓包名",
                scheme:"url scheme的scheme字段"
            },
            fallback:callBackUrl,
            appstore:"app store地址",
            yingyongbao:"应用宝地址"
        },
    callLib = new CallApp(options)
    callLib.open(openObj)
}
```
我和app小伙伴约定了schema的协议和主机字段，你那里没有填scheme.host，确定可以吗？虽然库不要求必填……
我当初和app小伙伴开发的时候试过，不设置host反而没法唤起，因此填了host就可以了
安卓和ios用的都是url schema的形式
另外就是你现在用的是什么方式完成的需求呢？

**Comment by suanmei** [comment]
你填了host就可以打开，我是否可以认为，你们 scheme 就是需要 host 才能打开的。我们完成需求主要是通过 ios 中的 universal Link 和 安卓中的 intent ，url scheme 的使用体验太差，所以你的精力应该主要放在督促 APP 开发同学去实现 universal Link ，找找资料一两天肯定可以实现
