### ISSUE TITLE
为什么不需要做弹框确认的处理呢？

### ISSUE THREAD

**Issue by zhengyanwen** [suanmei/callapp-lib#37]
很多情况会在你唤起APP的时候，会弹框询问是否确定要打开某个APP，点取消是算唤起失败还是什么？   这个弹框在整个唤起过程中处于什么位置呢，为什么代码里没有这个判断？求大佬解答

**Comment by suanmei** [comment]
点取消会被认为唤端失败，是否唤端失败是通过页面是否隐藏来判断的。

这个弹窗在APP唤起过程中属于鸡肋，只会让用户的操作链路变长，JS中没有API提供给你来判断是否有弹窗，判断了也没有什么意义。

而且很不幸的是，Universal LInk 现在也有弹窗了

**Comment by zhengyanwen** [comment]
@suanmei 
那有一种情况，在弹窗出来的时候，我既没有点击取消，也没有点击确定，而是直接按了手机home键退出，这种情况属于什么呢，也会被认为是唤端失败吗？

**Comment by suanmei** [comment]
这个你都可以自己测试得出来。
