### ISSUE TITLE
checkOpen 方法检测document.hidden问题

### ISSUE THREAD

**Issue by believeZJP** [suanmei/callapp-lib#4]
```javascript
const qqApp = new CallApp(qqOpt);

qqApp.open({
        path: '',
        param: {},
        callback: ()=>{
            Toast.info('请安装QQ')
        }
});
```

调用的时候设置了自定义的失败callback.

唤起成功时，也会出现提示框。

因为checkOpen时，网页还没有进到后台。document.hidden是undefined,导致还会调用callback.

**Comment by suanmei** [comment]
这个问题是由于自定义 timeout 引用错误导致的，而且 timeout 没有设置默认值

修复记录：
https://github.com/suanmei/callapp-lib/commit/22b01b5edcd7f06e4b04fc8ac0b0aa2fc87168da

**Comment by minlx** [comment]
@suanmei  重新下载包 V1.6.4 下载不了啊，大大

**Comment by suanmei** [comment]
> @suanmei 重新下载包 V1.6.4 下载不了啊，大大 document.hidden一直都是 false。。。。

下次不要在已经关闭的 issue 中 reply 撒，这样子收不到消息-_-

![callapp-lib](https://user-images.githubusercontent.com/19517557/47015538-d33f6880-d17f-11e8-9fc2-5715a3d560c1.png)

我今天中午下载还是可以的，包下载不了要么是 npm 的问题，要么是你的网络有点问题，后者可能性居多哈

document.hidden一直都是 false，你是用的哪个版本的

**Comment by suanmei** [comment]
> @suanmei 重新下载包 V1.6.4 下载不了啊，大大 document.hidden一直都是 false。。。。

下次不要在已经关闭的 issue 中 reply 撒，这样子收不到消息-_- 我先重新打开，回复你一下😄 

![callapp-lib](https://user-images.githubusercontent.com/19517557/47015538-d33f6880-d17f-11e8-9fc2-5715a3d560c1.png)

我今天中午下载还是可以的，包下载不了要么是 npm 的问题，要么是你的网络有点问题，后者可能性居多哈

document.hidden一直都是 false，你是用的哪个版本的包呢，又是如何检测 document.hidden 的呢

**Comment by minlx** [comment]
> > @suanmei重新下载包V1.6.4下载不了啊，大大document.hidden一直都是假....
> 
> 下次不要在已经关闭的问题回复撒，这样子收不到消息-_-我先重新打开，回复你一下😄
> 
> ![callapp-LIB](https://user-images.githubusercontent.com/19517557/47015538-d33f6880-d17f-11e8-9fc2-5715a3d560c1.png)
> 
> 我今天中午下载还是可以的，包下载不了要么是npm的问题，要么是你的网络有点问题，后者可能性居多哈
> 
> document.hidden一直都是false，你是用的哪个版本的包呢，又是如何检测document.hidden的呢

@suanmei 之前下的是1.6.1的版本 下载的时候指定版本号 下载不了

**Comment by suanmei** [comment]
> > > @suanmei重新下载包V1.6.4下载不了啊，大大document.hidden一直都是假....
> > 
> > 
> > 下次不要在已经关闭的问题回复撒，这样子收不到消息-_-我先重新打开，回复你一下😄
> > ![callapp-LIB](https://user-images.githubusercontent.com/19517557/47015538-d33f6880-d17f-11e8-9fc2-5715a3d560c1.png)
> > 我今天中午下载还是可以的，包下载不了要么是npm的问题，要么是你的网络有点问题，后者可能性居多哈
> > document.hidden一直都是false，你是用的哪个版本的包呢，又是如何检测document.hidden的呢
> 
> @suanmei 之前下的是1.6.1的版本 下载的时候指定版本号 下载不了

```
npm install --save callapp-lib@1.6.4
```
是这样吗

**Comment by suanmei** [comment]
```
npm install --save callapp-lib@1.6.4
```
应该是可以的哈，如果实在不行就

```
npm uninstall --save callapp-lib
npm install --save callapp-lib
```

最新版本，timeout 的问题已经修复了，你可以试一下哈，好了的话说一下，我关闭这个 issue

**Comment by minlx** [comment]
> ```
> npm install --save callapp-lib@1.6.4
> ```
> 应该是可以的哈，如果实在不行就
> 
> ```
> npm uninstall --save callapp-lib
> npm install --save callapp-lib
> ```
> 最新版本，timeout的问题已经修复了，你可以试一下哈，好了的话说一下，我关闭这个问题

好的，我下载试试，谢谢你啦

**Comment by believeZJP** [comment]
延时不会解决这个问题，打开APP返回网页后，过2s还会执行回调。我现在的解决方案是，监听visibilitychange事件，如果发生变化，则清除延时事件。
```javascript
    let timer = setTimeout(()=>{
            Toast.info({
                content: '请安装微信',
                duration: 500
            });
        },2000)
        document.addEventListener("visibilitychange", function() {
            clearTimeout(timer);
        });

```

**Comment by minlx** [comment]
> > ```
> > npm install --save callapp-lib@1.6.4
> > ```
> > 应该是可以的哈，如果实在不行就
> > ```
> > npm uninstall --save callapp-lib
> > npm install --save callapp-lib
> > ```
> > 最新版本，超时的问题已经修复了，你可以试一下哈，好了的话说一下，我关闭这个问题
> 
> 好的，我下载试试，谢谢你啦
已经可以下载了，但是callback 唤起app成功后还是会执行

**Comment by minlx** [comment]
> > > ```
> > > npm install --save callapp-lib@1.6.4
> > > ```
> > > 应该是可以的哈，如果实在不行就
> > > ```
> > > npm uninstall --save callapp-lib
> > > npm install --save callapp-lib
> > > ```
> > > 最新版本，超时的问题已经修复了，你可以试一下哈，好了的话说一下，我关闭这个问题
> > 
> > 
> > 好的，我下载试试，谢谢你啦
> > @suanmei 已经可以下载了，但是callback 唤起app成功后还是会执行

**Comment by believeZJP** [comment]
另外在Android里测试的时候发现有的浏览器已经装了，但是无法唤醒，在没有安装应用宝的情况下没有跳转到应用宝，直接走了option中的fallback的网址。
```javascript
// 微信配置
const weixinOpt = {
    protocol: 'weixin://',
    intent: {
        package: 'com.tencent.mm',
        scheme: 'weixin://'
    },
    appstore: 'https://itunes.apple.com/cn/app/id414478124',
    yingyongbao: 'https://a.app.qq.com/o/simple.jsp?pkgname=com.tencent.mm',
    fallback: location.origin
};

weixinApp.open({
        path: '',
        param: {},
})
```
@suanmei

**Comment by suanmei** [comment]
> 延时不会解决这个问题，打开APP返回网页后，过2s还会执行回调。我现在的解决方案是，监听visibilitychange事件，如果发生变化，则清除延时事件。
> 
> ```js
>         let timer = setTimeout(()=>{
>             Toast.info({
>                 content: '请安装微信',
>                 duration: 500
>             });
>         },2000)
>         document.addEventListener("visibilitychange", function() {
>             clearTimeout(timer);
>         });
> ```

好的，我这么处理一下

**Comment by suanmei** [comment]
> yingyongbao

现在没有库可以满足所有场景下的唤端，总会有不满足的哈~

> 在没有安装应用宝的情况下没有跳转到应用宝，直接走了option中的fallback的网址

应用宝是只有在微信中打开app不成功的情况下才会跳转应用宝地址，可以看一下库里面对各种场景的处理~

**Comment by suanmei** [comment]
> > > > ```
> > > > npm install --save callapp-lib@1.6.4
> > > > ```
> > > > 应该是可以的哈，如果实在不行就
> > > > ```
> > > > npm uninstall --save callapp-lib
> > > > npm install --save callapp-lib
> > > > ```
> > > > 最新版本，超时的问题已经修复了，你可以试一下哈，好了的话说一下，我关闭这个问题
> > > 
> > > 
> > > 好的，我下载试试，谢谢你啦
> > > @suanmei 已经可以下载了，但是callback 唤起app成功后还是会执行

你现在再试一下🤣我回家了，不在公司，测试机不在

**Comment by suanmei** [comment]
ios 自测已修复，安卓身边暂时没测试机

**Comment by suanmei** [comment]
1.6.6 已发布，如上所述问题已经fix
 @minlx @believeZJP
