### ISSUE TITLE
关于唤起优先级的疑问

### ISSUE THREAD

**Issue by MillionQW** [suanmei/callapp-lib#41]
https://github.com/suanmei/callapp-lib/blob/291baa0e1c9e14820535b8d0bb4c49d715ddf68c/index.js#L120

在看代码的时候发现安卓下的判断逻辑是 原生Chrome浏览器走<a>表签唤起，不是才走iframe。是否说明原生Chrome浏览器下<a>唤起的成功率更高，而在第三方浏览器下使用iframe成功率更高呢？

感谢作者对开源的贡献~

**Comment by suanmei** [comment]
安卓自带浏览器中很多都是谷歌原生内核，这些都是支持 intent 的，intent成功率远高于 url scheme

**Comment by MillionQW** [comment]
我是否可以把intent等价理解为App Link？
我目前的情况是客户端那边如果支持App Link和universal Link，就不调起中转页，只要调了中转页就一定是走deepLink，这种情况下安卓苹果是不是都走 ```evokeByIframe``` 更好？

**Comment by suanmei** [comment]
Intent 是chrome的App Link
你的中转页是什么，能多提供一些信息吗。因为我不太清楚你是因为流程导致的，还是受限于客户端的实现

**Comment by MillionQW** [comment]
是的，客户端的实现可以让支持App Link和universal Link的直接调起APP。不走中转页。
问题其实可以简化为，只使用deepLink的情况下，安卓苹果是不是都走 ```evokeByIframe``` 更好？

**Comment by suanmei** [comment]
嗯，是的

**Comment by MillionQW** [comment]
好的，感谢解答！

**Comment by MillionQW** [comment]
@suanmei 在我的实际测试中，XR用<a>标签才能成功调起APP，用iframe反而不行？

**Comment by suanmei** [comment]
XR我这里可以呦，你那边实在不行，可以判断一下XR，然后特殊处理一下，使用evokeByTagA。不要两个一起调用，可能会有怪异的表现

**Comment by MillionQW** [comment]
想请问下```evokeByTagA```调deepLink在Chrome下调不起APP，是不是一定要用用户的手势触发才可以呢？

**Comment by suanmei** [comment]
A标签模拟点击就是手势操作，参照 #28

**Comment by MillionQW** [comment]
咦... ```tagA.onclick();``` 我在小米的手机Chrome浏览器deeplink调不起来APP，用一个<a>标签手动点击才可以....

**Comment by suanmei** [comment]
最好的解决办法是让客户端同学去支持厂家推广的技术解决方案。
url scheme 算是一种降级方案，不能保证所有浏览器都能正常唤起，如果你有找到好的解决办法，欢迎提PR。

**Comment by MillionQW** [comment]
嗯嗯，我们这边目前是把 deepLink 做为最后的兜底方案，如果App Link调不起就打开链接，用deepLink跳转，同时打开H5页。

提个case，fackbook的webview不支持deeplink打开，会报“无法加载页面”然后退出webview~我的处理方法是判断当前是否在fb的webview下，如果是的话直接跳H5，不走deeplink。
