### ISSUE TITLE
ios微信跳转应用宝唤端

### ISSUE THREAD

**Issue by ellyye** [suanmei/callapp-lib#42]
appLink提供了android_schema和ios_schema
安卓微信是跳应用宝唤起指定app页面，ios微信目前是跳转appstore
建议ios也跳转应用宝，应用宝会提示在safari打开，safari打开后再尝试唤起指定app页面

**Comment by suanmei** [comment]
ios 中无法下载 应用宝

**Comment by ellyye** [comment]
不需要下载应用宝，只需要通过应用宝网页唤端
试过可行：https://s.codepen.io/ellyye/debug/arZegw/wQrPoNXDwgNM

**Comment by suanmei** [comment]
打开你的地址试了下，不行，应用宝提示去app store下载

**Comment by ellyye** [comment]
![image](https://user-images.githubusercontent.com/26915448/57701713-22eeff80-768f-11e9-9ec4-97f6e89ba62d.png)
试了右上角的在safari打开？

**Comment by suanmei** [comment]
你的地址失效了，方便再发一版吗

**Comment by suanmei** [comment]
支付宝网页端可以唤端，也是通过scheme来唤起的。你在微信中自己搞一个中转页。这个中转页提示在safari打开，然后通过scheme，这样比的话应用宝并没有什么优势，安卓微信使用应用宝是因为应用宝在安卓中用户量还是蛮大的。如果中转页通过universal Link来实现，在safari打开的同时就能唤起app，还省去了一步操作

**Comment by ellyye** [comment]
同意你的意见，ios qq里打开微下载页没有引导safari打开，针对这种情况还是得自己做一个引导页
ios微信、qq唤端时跳转引导页，有没比较好的扩展方式

**Comment by suanmei** [comment]
这个引导就和唤端库关系不大了，你有两种做法可以实现，第一种是做一个普通的引导页，让他通过微信直接在safari中打开，引导页一进入就调用 scheme ，实现唤端。第二种是，引导页的地址本身就是一个Universal Link，通过通信在safari中打开这个步骤本身对于universal Link来说，算是点击调用，是可以直接唤端的
