### ISSUE TITLE
关于唤端失败跳转应用宝/app store的问题

### ISSUE THREAD

**Issue by SilentFlute** [suanmei/callapp-lib#51]
哈喽哈喽，距离上一次的`issue`已经过去了3个月了，关于唤端最近遇到了一个问题，故又来骚扰你了🤣🤣
# js版本
"callapp-lib": "^2.1.5"
# 配置代码
```
export const handleCallApp = (path = "", param = null) => {
    let openObj = param
            ? {
                path,
                param
            }
            : {
                path
            },
        callBackUrl = "ios就是app store地址，安卓就是应用宝地址",
        options = {
            scheme:{
                protocol:"url scheme的scheme字段",
                host:"url scheme的host字段"
            },
            intent:{
                package:"安卓包名",
                scheme:"url scheme的scheme字段"
            },
            fallback:callBackUrl,
            appstore:"app store地址",
            yingyongbao:"应用宝地址"
        },
    callLib = new CallApp(options)
    callLib.open(openObj)
}
```
配置代码还是之前的，只是做了参数的处理，因为有的页面需要传参，有的不需要
# 遇到的问题
当点击打开APP的按钮，调用我写的这个唤端的方法，浏览器会弹出提示框，当用户点击打开，那就走正常的流程，有的能直接打开app，有的要经过应用宝/app store再打开app，有的打开失败停留到应用宝/app store页面
但是当用户点击取消的时候，我看了其他的问题，发现点取消是算唤起失败，会走失败回调对吧？可是：
## 安卓
这里我用我自己的安卓手机，用uc浏览器试的，提示框出来点击取消，不打开app，此时会跳转到应用宝，失败回调执行了！后退的时候再次点击打开app，依旧是到应用宝，刷新页面也不行，非要关闭浏览器重新打开网页重新唤端才行
## ios
ios的safari，弹出提示框之后点击取消，此时地址栏里闪一下，然后弹出一个错误提示`Safari浏览器打不开该网页, 因为网址无效`，录屏之后反复观摩(🤣🤣)发现闪的那一下：
能看到`itunes.apple.com`以及`itms-appss://apps.apple.com/cn/app/我司ios应用app store的部分内容`，因为屏幕窄，所以只能看到这些，第二个出现之后错误弹窗才出现的，但是为何会有第一个出现，以及第一个和第二个url之间什么关系我暂时没弄明白🤣🤣
对比我司的ios应用app store的地址:`https://itunes.apple.com/cn/app/xxx`发现：
1. 第一个url为商店的域名
2. 第二个比较奇怪，只符合商店地址的后面部分`apple.com/cn/app/xxx`但是是不是完全比配商店地址的后半部分我不确定，因为屏幕窄，没能看全……

但是能确定的是无论哪个url都不是我司应用的商店地址，如果是了，也就打开商店了，而不会报错了对吧？
所以大佬能不能帮忙看下有没有什么思路可以解决这两个问题：
1. 安卓取消之后需要退出浏览器再点打开app才能重新进入唤端流程
2. ios点取消之后浏览器打开的不是app store的地址

万分感谢

**Comment by SilentFlute** [comment]
升级库到`2.1.7`
使用浏览器调试，模拟苹果手机，页面上直接写一个a标签到商店地址，或者点击事件中window.top.location.href到商店地址，均会发生重定向
先是打开商店地址：`https://itunes.apple.com/cn/app/xxx?查询字符串`
然后301接着重定向到了：`itms-appss://apps.apple.com/cn/app/xxx`
后面这个地址看起来似乎是一个唤起app store的url schema，后来百度了一下发现真的是
参考该问题：#50 ，没装app点打开尝试唤端也会报这个错，但是装了app，点了弹窗的打开之后的唤端失败却不会，却能去到app store，既然如此，那我将失败回调`fallback`中ios的失败回调我就直接写成唤起app store的这个schema就好了吧，这样的话点击唤端：
1. 没装app，唤端失败，走失败回调→打开了app store
2. 装了app，提示窗中点的是取消，没点打开(因为只有装了app才会有两个选项的提示框，没装直接报错)→依旧能打开app store

后来尝试之后发现
1. 没装app, 点击打开app的按钮也是报错
2. 装了app, 点取消依旧打开的是app store，还是有重定向

于是我把`fallbak` `appstore`的地址都换成唤起app store的schema了再次尝试
1. 没装app, 依旧报错
2. 装了app, 点取消, 依旧是报错

但直接在点击事件中写window.top.location.href到唤起app store的schema却是对的，能唤起app store
因此推测是先发了一个唤起app的schema，唤起失败此时导致打开两种app store的链接都失败，都报错，因此尝试如下操作：
```
    onClick={() => {
        window.top.location.href = "ios的url schema";
        setTimeout(() => {
            window.top.location.href = "唤起app store的url schema"或者是"app store的链接";
        }, 5000)
    }}
```
由于装了app，会弹出是否打开app的提示，此时点击取消关闭提示窗，然后会打开`setTimeout`中的链接，此时就会报错了
所以就是
1. 没装app, 一定报错
2. 装了app, 只要做了唤端的动作但是点了取消导致没能成功唤端，那么后面跳转的app store的地址或者尝试唤起app store都会报错，都会失败，但是打开的如果是其他页面，比如腾讯什么的就是ok的

另外就是此次调试还发现了一个问题: ios成功打开app之后, app启动页还没加载出来便会从app又跳转到app store, 安卓暂时没发现, 看起来像是没有成功检测到页面隐藏然后清除延时器, 导致程序以为唤端失败从而错误执行了唤端失败的回调
求指点🤣🤣

**Comment by SilentFlute** [comment]
另外就是app store链接301重定向这个问题一直存在，只是在做了唤端的动作并点取消之后没法正常打开app store和app store的url schema
链接重定向的问题电脑端浏览器中也存在🤔🤔

**Comment by SilentFlute** [comment]
然后我想了个奇淫巧技，将超时时间设置为8.64e7，也就是1天，这样当提示是否打开app的时候点取消，此时的时间差不会是1天，那么就不会走失败回调，哪怕发起了一次唤端操作，因此就没问题了不会报错了
以及打开app了又跳回app store的问题也搞定了，因为不管页面隐藏事件是否成功执行，延迟时间都没到，所以不会执行失败回调，但……你懂得🤣🤣

**Comment by suanmei** [comment]
@SilentFlute 是这样哈，有一个节点你可能理解错了，没安装app，点击唤端，并不是跳转到 app store 的 schema， 而是你调用的 app 的那个 schema 然后报错。

**Comment by suanmei** [comment]
> 另外就是app store链接301重定向这个问题一直存在，只是在做了唤端的动作并点取消之后没法正常打开app store和app store的url schema

这个问题我去年本地开发的时候也发现过，苹果自家的问题，而且不是必现，可能成功可能失败

**Comment by suanmei** [comment]
> 打开app了又跳回app store的问题
这个是什么问题，挺好奇的，有研究过是为什么吗？

然后再说一嘴，苹果一直在推 universal Link，ios 9以下，如果你没有安装app，打开schema都是不会报错的，报错是从 ios 9 开始的，某种程度上可以理解为苹果在恶心继续使用 schema 的用户。

你们也开发这么久了，universal Link 抽个两天时间实现一下应该没有那么难吧。。。

**Comment by SilentFlute** [comment]
嗯，通用链接
那安卓呢，app link大陆没法用，要翻墙，是不是就url schema了还是intent？求指点！
通用链接就是最近我手上其他任务还有，遗留bug和新的重构任务应接不暇，app的又有其他的紧急业务在搞(公司不紧气，之前的app同学被裁了……🤣🤣)，大家都忙不过来，这次这个报错是测试妹子突然提出来的，也不知道为何唤端版本的时候没有测出来

**Comment by SilentFlute** [comment]
> 你填了host就可以打开，我是否可以认为，你们 scheme 就是需要 host 才能打开的。完成唤端应该主要通过 ios 中的 universal Link 和 安卓中的 intent ，url scheme 的使用体验太差，所以你的精力应该主要放在督促 APP 开发同学去实现 universal Link ，找找资料一两天肯定可以实现

url schema确实体验差，安卓intent，ios通用链接，好的，了解了，多谢大佬的指点，后面再来个版本专门做唤端吧，现在前端和app都有各自的事，后面如果有问题再来向大佬请教啦，再次感谢
