### ISSUE TITLE
请教下，如下的scheme该如何写到option里

### ISSUE THREAD

**Issue by danzhoua** [suanmei/callapp-lib#53]
exuecloud://splash?thirdId=123&isBind=456

url scheme协议是这种形式的，请教下thirdId=123&isBind=456该放到option里的何处

**Comment by suanmei** [comment]
https://github.com/suanmei/callapp-lib/blob/master/README.md#open

> param
    类型: object
    必填: ❎
    打开 APP 某个页面，它需要接收的参数。

把 `{ thirdId: 123, isBind: 456}` 作为 `param` 传递给 `open` 函数
