### ISSUE TITLE
安卓手机唤起失败无法跳转页面失败链接

### ISSUE THREAD

**Issue by yixinagqingyuan** [suanmei/callapp-lib#59]

**Comment by suanmei** [comment]
按照最新的 issue 模板来写

**Comment by yixinagqingyuan** [comment]
大佬，您好，安卓端除了微信浏览器外别的浏览器无法唤起失败回调原因已经找到
	const isOriginalChrome = /chrome\/[\d.]+ Mobile Safari\/[\d.]+/i.test(ua) && isAndroid && ua.indexOf('Version') < 0;
就是这个判断浏览器的正则导致，不知是否有别的用意，求大神指点

**Comment by suanmei** [comment]
这个是用来判断chrome内核的，现在安卓各个厂商自家的自带浏览器以及其他浏览器，没有一个统一的标准，很难判断究竟该用scheme还是intent来唤端，这个后面会通过尽可能罗列市面上的主流App的方式来进行排除

**Comment by suanmei** [comment]
https://github.com/suanmei/callapp-lib/commit/6aea256446f0d78a3ea902cb3a9c2b527036f087  已修复
