### ISSUE TITLE
universal link 的拼接方式 为什么如此奇怪

### ISSUE THREAD

**Issue by ourfeel** [suanmei/callapp-lib#60]
path 部分居然是通过qs进行传递。
知乎ulk 地址： https://oia.zhihu.com/answers/762544468

**Comment by suanmei** [comment]
传参方式永远只是方式，URL 只是媒介，如何传递取决于和客户端约定如何实现通过 Universal Link 实现唤端。知乎是通过path来区分，我这里是通过query来传递

**Comment by ourfeel** [comment]
> 传参方式永远只是方式，URL 只是媒介，如何传递取决于和客户端约定如何实现通过 Universal Link 实现唤端。知乎是通过path来区分，我这里是通过query来传递

所以这块不够灵活。 是不是应该遵循URI的拼接，如果path有放在qs的特殊需求， 可以自行处理。
目前如果要实现path区分。把完整的 href 直接赋值给了host。不是那么好

**Comment by suanmei** [comment]
Good idea！不过这个属于break级别的change，我这边需要做一些兼容。对这个库还有其他的建议吗😄

**Comment by ourfeel** [comment]
比如针对 yingyongbao 和 appstore 地址为空 不操作

**Comment by zfan40** [comment]
非常感谢作者整理，+1这种兼容方式，时间好像挺长了 不知道作者有没有计划优化，貌似目前对于path这类只能把path写到option.universallink.host里面
