### ISSUE TITLE
唤醒 跳转指定页面失败，回调却不执行

### ISSUE THREAD

**Issue by YingDreamyoung** [suanmei/callapp-lib#61]
+ 版本号: callapp-lib@
2.1.17
+ 配置Option: 
{
  path: '../index/articleDetail',
		param:{	
				id: parseInt(articleId),
				data: {}
		},
callback: ...
}
``` json
 {
  "scheme": {},
  "outChain": {},
  "intent": {},
  "universal": {},
  "appstore": "",
  "yingyongbao": "",
  "fallback": ""
 }
```

+ 机型、系统、APP:
ios phonex 
+ 遇到的问题及复现步骤:
h5 页面，点击提示，网址错误
+ 期望的效果:
 如果指定的页面打不开，不应该是走回调吗，然后跳转到，appstore 的位置。

请大佬赐教

**Comment by suanmei** [comment]
你把你的 Option 贴一下，你给我的是你调用函数时候的 param 。

然后追加一下，你是否有安装该APP，你是在 iphone 的哪里点击的唤端（比如微信，safari...）

**Comment by YingDreamyoung** [comment]
ok! 我明白了，我这里还发现了一个问题，就是小米系列的，都是没法唤醒的，基本都是走的回调函数，我的回调时间是2000ms ，这里能不能有更好的效果，请大佬解疑，谢谢

**Comment by suanmei** [comment]
嗨，是小米系的原生浏览器打不开吗

**Comment by YingDreamyoung** [comment]
是的

**Comment by suanmei** [comment]
应该是判断原生谷歌浏览器的正则导致的，安卓各家浏览器没有统一的标准，无法通过一个正则精准匹配，接下来会优化一下

**Comment by YingDreamyoung** [comment]
嗯，我发现浏览器检测工具，测试小米的浏览器，系统检测是 linux 的,检测浏览器确实是谷歌的，大佬，我这边能快速解决这个问题吗，能指点一下吗

**Comment by suanmei** [comment]
我今晚尽量给你改一下，这块判断各家浏览器很费劲

**Comment by YingDreamyoung** [comment]
大佬，我发现，华为的机子，也是不行的 mate9（安卓9，无法唤起app），华为 v8(安卓8 ,可以唤起app,不能到指定的页面)，小米9 (安卓9),都是不行，不知道这样能不能帮到你

**Comment by suanmei** [comment]
哈哈。好的，我都会记录下来的

**Comment by YingDreamyoung** [comment]
大佬，昨天晚上加班了没，等你好消息

**Comment by jyhu1993** [comment]
![image](https://user-images.githubusercontent.com/39950693/62200792-b72c5100-b3b8-11e9-9afc-e48f5d1d0842.png)
请问appStore和yinyongbao这两个参数文档上为什么是必填，我把这两行注释掉似乎也是可以的

**Comment by cody1991** [comment]
一加手机的也是这样 直接调用 lib 的话走的都是失败的回调

但是如果绑定在某个 click 时间上就是正常打开app的

即使是 btn.click() 模拟 也是打开不了

上面的描述是在 一加手机 上的 Chrome 浏览器，原生的是正常的

不过又发现他们的浏览器信息是基本没啥区别的。。

现在全部换成点击来触发（是一个中间跳转页面，原本应该是直接就跳转了） 也是好郁闷

**Comment by suanmei** [comment]
> 大佬，昨天晚上加班了没，等你好消息

搞了一半，搞完还要测，我也在加油😂

**Comment by suanmei** [comment]
@YingDreamyoung 我发现不是我的库的问题，因为我这边测试了你说的几个机型，我这边的功能都正常，你先把你的Option贴出来，不是open方法的入参，是你初始化时候的参数

**Comment by suanmei** [comment]
@cody1991 看一下 #15 ,非常不建议进入就自动唤端

**Comment by suanmei** [comment]
@YingDreamyoung @jyhu1993 @cody1991 加QQ群779888136细说

**Comment by YingDreamyoung** [comment]
大佬，在你的启示下，我完成了我这边的测试，具体的代码，等在群里，在讨论吧
