### ISSUE TITLE
安卓浏览器跳转异常

### ISSUE THREAD

**Issue by anbeitadie** [suanmei/callapp-lib#62]
+ 版本号: callapp-lib@

+ 配置Option: 

``` json
 {
  "scheme": {
      "protocol": 'taobao',
  },
  "outChain": {},
  "intent": {},
  "universal": {},
  "appstore": 'https://itunes.apple.com/cn/app/微信读书/id952059546?mt=8git s',
  "yingyongbao": '//a.app.qq.com/o/simple.jsp?pkgname=com.youku.shortvideo',
  "fallback": 'https://weread.qq.com/',
  "timeout": 5000,
 }
    const lib = new CallApp(option);
    const callButton = document.querySelector('#call-button');
    callButton.addEventListener('click', () => {
      lib.open({
        path: ''
      });
    });
```

+ 机型、系统、APP:

+ 遇到的问题及复现步骤:
open.path不带参数，在安卓机（oppo）中自带浏览器中无法实现拉起，然后qq浏览器中可以实现拉起淘宝但是会显示：下个页面不受我们控制，使用时请注意安全http://。点击确认后会跳转到浏览器并且域名为http://。ios机型则正常拉起淘宝
+ 期望的效果:
本人小白一枚，希望大佬耐心解答！感谢！

**Comment by anbeitadie** [comment]
如果是没写indent的问题，那么我想问一下indent里的package应该怎么写，感谢！

**Comment by anbeitadie** [comment]
刚刚安卓机试了一下，uc浏览器正常拉起，qq浏览器能提示跳转但不跳转，自带浏览器点击则没反应，请大佬解答，感谢！

**Comment by anbeitadie** [comment]
刚刚安卓机试了一下，uc，qq浏览器正常拉起，oppo r11无法拉起，无法拉起失败跳转
Mozilla/5.0 (Linux; U; Android 8.1.0; zh-cn; OPPO R11st Build/OPM1.171019.011) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.134 Mobile Safari/537.36 OppoBrowser/10.5.0.4
这是浏览器的UA
请大佬解答！

**Comment by anbeitadie** [comment]
刚刚试了一下，华为的自带浏览器也无反应，UA也是Mobile Safari结尾的

**Comment by suanmei** [comment]
各位的issue都已收到，需要时间，周末发版！

**Comment by anbeitadie** [comment]
因为公司需要，所以想实现安卓微信内拉起app，如果跳h5拉起，那可能bug多（比如上面提到的浏览器问题），而且达不到公司需求！感谢！

**Comment by suanmei** [comment]
> 因为公司需要，所以想实现安卓微信内拉起app，如果跳h5拉起，那可能bug多（比如上面提到的浏览器问题），而且达不到公司需求！感谢！

如果进不了微信白名单的话，安卓端这个事情就不用考虑了。目前ios端是可以的

**Comment by suanmei** [comment]
@anbeitadie 我检查了一下你的配置，你的问题不是出在我的库上，而是你没有配置正确，intent没有的话就不要传，这一点我在文档里有提到

**Comment by suanmei** [comment]
进一步讨论 加QQ群779888136

**Comment by anbeitadie** [comment]
按照你的来，我仅仅传了一个scheme参数，没有传intent，在安卓oppo自带浏览器也是拉不起来，跳到fallback，其他浏览器可以，出现的问题跟我上面的是一样的；
查不到群，只能查到一个人
![image](https://user-images.githubusercontent.com/31610490/62432436-4a230d80-b762-11e9-8476-00acaca068a8.png)

**Comment by suanmei** [comment]
现在可以搜到了，现在的QQ不太会用了😄

**Comment by xieyanxieyan** [comment]
小米、oppo、努比亚、联想等机型，用手机的自带浏览器，运行作者的例子，点了按钮没反应，这个应该是兼容性问题吧？现在有解决办法么

**Comment by suanmei** [comment]
@xieyanxieyan 有解决办法，最近没时间，计划是在九月解决

**Comment by TothingWay** [comment]
@suanmei 请问这个问题解决了吗？

**Comment by suanmei** [comment]
有点击无效的大家统一罗列到这个issue https://github.com/suanmei/callapp-lib/issues/94 中哈，谢谢大家。

提交之前确保是库的问题而不是配置错了，验证的话，访问 https://callapp.netlify.app/ 来唤起知乎试验一下
