### ISSUE TITLE
微信universal link唤起问题

### ISSUE THREAD

**Issue by anbeitadie** [suanmei/callapp-lib#63]
+ 版本号: callapp-lib@

+ 配置Option: 

``` json
 {
  "scheme": {protocol: 'taobao'},
  "outChain": {},
  "intent": {   
        package: 'com.taobao.taobao',
        scheme: 'taobao'
                 },
  "universal": {
          host: 'm.tb.cn/h.eRGdcWF',
          pathKey: 'sm=8e634e',
},
  "appstore": 'https://itunes.apple.com/cn/app/微信读书/id952059546?mt=8git s',
  "yingyongbao": "",
  "fallback": ""
 }
```

+ 机型、系统、APP:
ios12
+ 遇到的问题及复现步骤:
使用universal Link在微信中打开并未跳转淘宝，而是直接提示跳转app store，在浏览器中打开则可以跳转至淘宝相应页面
+ 期望的效果:
望解答为什么微信中没效果，感谢！

**Comment by suanmei** [comment]
希望好好看文章，文章里面已经讲了，微信禁止了URL Scheme以及Universal Link，所以我们就不去尝试唤端了，在ios中直接打开 itunes 了。

但是，微信最新版本放开了Universal Link的限制，我这边还没来得及调整，周末和其他issue统一处理

**Comment by anbeitadie** [comment]
嗯，期待大佬的调整，还有个问题，如果不用URL Scheme以及Universal Link和白名单，是不是就无法在微信内拉起app，一点办法也没有，安卓的话，在微信内拉起，有没有好的办法！

**Comment by suanmei** [comment]
撇开白名单不说，目前为止能够在微信中唤起app的方式就是在ios端微信中通过universal link方式唤端，换一种唤端方式，或者在安卓端都不可以

**Comment by anbeitadie** [comment]
大佬咋还没发版嗷
