### ISSUE TITLE
UC Turbo浏览器 - 直接用Demo测试 点击无反应

### ISSUE THREAD

**Issue by BeijingBigBorther** [suanmei/callapp-lib#65]
直接用Demo测试 点击无反应

+ 机型、系统、APP:
三星 SM-J730F/DS 8.1.0
浏览器信息：UC turbo 1.6.3.900 Base on U4 2.0 kernel
+ 遇到的问题及复现步骤:
直接用Demo测试 点击无反应

**Comment by suanmei** [comment]
机型问题汇总到这个issue https://github.com/suanmei/callapp-lib/issues/94 ，谢谢啦
