### ISSUE TITLE
安卓不跳转应用宝，直接跳转下载链接，该库该怎么使用

### ISSUE THREAD

**Issue by daughterRui** [suanmei/callapp-lib#66]
安卓不跳转应用宝，直接跳转下载链接，该库该怎么使用

**Comment by CodingZJ** [comment]
@daughterRui 拟解决了吗？同问

**Comment by suanmei** [comment]
commit：https://github.com/suanmei/callapp-lib/commit/b7943336b84f0a04b9e4411e3dcd761e8c0a532d
line：https://github.com/suanmei/callapp-lib/blob/master/src/index.ts#L98

新加了一段逻辑，yingyingbao  这个字段不配置就可以了，不配置yingyongbao，在安卓微信中不会跳转应用宝地址，会直接跳转fallback
