### ISSUE TITLE
IOS iphone8p 如何避免Safari浏览器打不开该网址，因为网址无效的弹窗

### ISSUE THREAD

**Issue by lsqtongxin** [suanmei/callapp-lib#68]
+ 版本号: callapp-lib@2.1.8

+ 遇到的问题及复现步骤:
当ios里面不存在app时，打开h5页面会出现Safari浏览器打不开该网址，因为网址无效，然后跳转appStore。
当ios已安装app时，打开h5页面会出现 在“某某应用”中打开链接吗？“取消”or“打开”

+ 期望的效果:
当ios里面不存在app时，打开h5页面会自动跳转appStore，避免网址无效的弹窗。
当ios已安装app时，打开h5界面自动直接跳转到app，避免弹窗

核心诉求是避免无效的弹窗

**Comment by ourfeel** [comment]
通过scheme 方案 。 在IOS9后就无法避免无效弹窗。
ios弹窗确认 是系统行为

**Comment by suanmei** [comment]
两种弹窗都是系统行为，不可控
