### ISSUE TITLE
此库想唤起 RN APP ，怎么 集成啊 ?

### ISSUE THREAD

**Issue by cham1985** [suanmei/callapp-lib#69]
我现在的 app 是 RN 搭建的，安卓怎么集成代码完成h5 拉起啊 ？

**Comment by zhenghui0705** [comment]
### 参照 RN官方文档 Linking 用法

componentDidMount() {
    Linking.addEventListener("url", this._handleOpenURL);
  }
  componentWillUnmount() {
    Linking.removeEventListener("url", this._handleOpenURL);
  }

  // 监听唤醒 App 传递的参数
  _handleOpenURL(event) {
    try {
      const dd = event.url;
      const queryObj = {};
      const reg = /[?&]([^=&#]+)=([^&#]*)/g;
      const querys = dd.match(reg);
      if (querys) {
        for (let i in querys) {
          let query = querys[i].split("=");
          let key = query[0].substr(1),
            value = query[1];
          queryObj[key]
            ? (queryObj[key] = [].concat(queryObj[key], value))
            : (queryObj[key] = value);
        }
      }
      if (typeof queryObj === "object" && typeof queryObj.pid != "undefined") {
        // 拿到 pid 跳转到商品详情
        Actions.ProductDetails({
          pid: queryObj.pid
        });
      }
      console.log(dd, queryObj, "外部H5传递过来的参数");
    } catch (error) {
      console.log(error, "外部H5传递过来的参数");
    }
  }
