### ISSUE TITLE
ios唤端

### ISSUE THREAD

**Issue by SilentFlute** [suanmei/callapp-lib#7]
我司需要做一个引流的操作，也就是唤端的操作，安装`app`了，那么打开，没有安装那么跳到下载页面，`ios/安卓`都有这个需求，目前在和`ios`的伙伴先做，我们都是第一次做这个，都是在没有石头可摸的情况下硬过河……
`ios`使用通用链接的配置，如下：
![image](https://user-images.githubusercontent.com/28900312/47842234-1132c280-ddf7-11e8-895d-a1d6dfb76d8f.png)
我这边的配置如下，虽然看了你的文章了，但是还是N多地方不懂：
![image](https://user-images.githubusercontent.com/28900312/47842476-b2217d80-ddf7-11e8-8b77-cab9c90be234.png)
我用的`react`，然后点击事件中调用`handleCallApp`方法，在里面唤端，因为只是先做`ios`的，所以`安卓`的就写了个应用宝的地址
- 你这个库，失败的处理，默认是什么？默认是`appstore`吗？我的理解失败就是没有`app`，然后就让用户下载…
- 要是只是打开`app`，先不指定`app`的哪个页面，那`pathKey`配置为`*`行吗？还是直接不写`pathKey`就好？
- `callLib.open`里面，那个`path`: `需要打开的页面对应的值`，就直接打开`app`就好，暂时不指定页面，这里填`*`可以吗？
- `callLib.open`里面的`param`，由于暂时没有指定页面，所以我没填…
- `callLib.open`里面的`callback`， 由于不确定默认的失败回调是什么，所以没写
`ios`那边他找了一些配置`通用链接`的文章，我看了下配置清晰，应该不会配错吧；我如上配置，`ios`同学装上他写了代码的`app`，然后测试的时候都是跳到应用宝，然后页面提示`在App Store中打开链接吗？`点确定就跳到`app store`，然后那有个下载的按钮，然而我要是不用你的这个唤端库，直接：
```
const handleCallApp = () => {
    window.location.href = '我司app的应用宝链接'
}
```
那跳到`app store`之后还会有个打开按钮，所以我们这是哪里搞错了呢？问题比较多，望见谅，求回复，谢谢啦

**Comment by suanmei** [comment]
一个一个回答哈
1. 关于 universal Link 的配置，可以看一下，[官方开发文档](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12-SW2)

2. 然后关于 callapp-lib 实例化需要传入的 option ，在 #6 中我已经给出了示例，你可以借鉴一下。在 callapp-lib 的 Readme 中，写了必传的参数，都是需要传递的，否则唤端库会报错，所以你需要补全那些属性，瞎填也行（比如这个属性要求 string 类型，你可以填一个 ''）

3. 失败的处理，不同的系统，不同的唤端平台（微信、浏览器 etc.）是不一样的，ios 中的微信是默认打开 APP strore，当然你可以传递自定义的失败回调函数，它会替代默认失败回调。

4.  > 要是只是打开app，先不指定app的哪个页面，那pathKey配置为*行吗？还是直接不写pathKey就好？

这个随便填一个 字母吧， `*` 会不会影响，我也不太确定

5.  > callLib.open里面的param，由于暂时没有指定页面，所以我没填…  

param 不是必填的，这个时候你应该传递 `path: ''`，不要带 `*`。

6. callback 是自定义失败回调，不需要自定义，不需要传递这个属性

**Comment by suanmei** [comment]
@SilentFlute 刚刚发了一版，最新版，open 方法中 path 已经不是必填的了

**Comment by suanmei** [comment]
按照上面我说的，你都修改后，应该不会有跳转问题了。如果能唤起app成功，说明 ios 和你都配置正确，不能唤端分两种情况，Universal Link 本质上也是一个 url，如果是跳到这个 url 了，说明你这边没问题，ios那边有问题；如果出现其他情况，就是你这边配置有问题了

**Comment by SilentFlute** [comment]
刚又和`ios`同学确认了下，他说备忘录唤端失败……，另外就是我这么写：
```
…
    switch(isIOS) {
        case true:
            callLib.open({
                path:""
            })
            alert(111)
            break
…
```
在`chrome`中模拟手机，选择`iphone`的时候，弹出`111`了，`is.ios()`确实是返回的`true|false`，不过发生了一件事，我这么做，`chrome`的`iphone`是没装我司软件的，那么算唤端失败，但是和我的预期不一样，它跳转到了一个网址：
`apple-app-site-association文件的域名?a=`的地址，也就是`options`中`universal`的`host`，参数是`options`中`universal`的`pathKey`的地址:`options.universal.host?options.universal.pathKey=`，唤端失败的`回调`不应该是我指定的那个配置里面的`fallback`的地址吗？就是我司`ios app`的`app store`的地址啊，总之为何会是`通用链接`配置文件所在的域名，不科学啊~~~

**Comment by suanmei** [comment]
@SilentFlute 既然他们 备忘录 唤端失败，就是他们那边还没有配置好哈。

然后说你的写法，没有说不对，只是说可以写的更优雅一点😂

chrome 模拟 iphone，这个毋庸置疑哈。然后 universalLink 本身的机制就是，能唤端成功就唤端，唤端不成功，他就会打开本身对应的页面， universalLink 本身就是一个 url。🍎家设计 universalLink 时就是这么设计的。至于为什么不打开 app store，直接打开 app store 是在 ios 微信中尝试唤端才会默认打开 app store

**Comment by SilentFlute** [comment]
哈哈哈，强迫症患者表示还是`switch case`的语句看起来更整洁😜😜
这个打开对应页面我感觉怪怪的,`https://xxx.xxx.com?a=`…
微信中唤端我试过，确实是会打开`app store`然后上面会提示你是打开还是怎样；你说的这个唤端不成功会打开本身对应的页面，`universal link`本身就是一个`url`，你的意思是就算在`ios`的`safari`中唤端，失败了也依然会打开`https://universal link域名?a=`这个链接？我的理解是：唤端失败了，那它不是应该跳`app store`让用户下载吗？如果还是打开`https://universal link域名?a=`这个链接那不坑爹了啊？
求指点~~~

**Comment by suanmei** [comment]
不是只在safari，ios9以上微信以外的地方都是使用的universal Link，唤端失败了都会跳转url所绑定的页面。

这个是 universal 的特性，它本身就是一个url，你需要看一下universal相关的知识，ios同学在开发者中心填写你们的这个域名，使用url的时候apple会查询这个url的域名是否是需要打开对应apple，如果是，初次使用的情况下会去尝试下载 apple-app-site-association这个文件，然后有了这个文件才能唤端。

这是它的机制。如果你想唤端失败，你就把这个universal Link重定向到一个中转页，这个中转页来自动跳转apple store。

还有判断 universal Link ios是否配置好了，就在备忘录里面测试吧。在微信中打开了app store，只能说明 callapp-lib 你配置对了😪和他们无关

**Comment by SilentFlute** [comment]
thx, 最近又在忙其他的项目，这个唤端的暂时搁浅了，后面还会再做，到时候再尝试，然后再来骚扰你哈😂😂

**Comment by SilentFlute** [comment]
hello大佬，又来骚然你了，最近PM催得紧，唤端再次被提上了日程
我和安卓，ios小伙伴暂时只考虑两个系统自带的浏览器，然后双方都使用url scheme的形式来唤端（毕竟通用链接ios小伙伴玩不转🤣🤣），都是点击唤起，不考虑传参打开指定页面什么的，就单纯的唤起app
# 配置情况
- 版本："callapp-lib": "^2.1.2"
- js代码如下：
```
    let options = {
        scheme:{
            protocol:"a",
            host:"b"
        },
        intent:{
            package:"安卓包名",
            scheme:"a"
        },
        appstore: "appstore地址",
        yingyongbao:"应用宝地址",
        fallback:"https://www.qq.com"
    },
    callLib = new CallApp(options)
    callLib.open({
        path:""
    })
```
- 安卓：和它一起约定了shceme以及host，他那边在配置文件里面配置了一下，没有其他业务代码
- ios：一起协商了scheme，没有host，ios就在那个开发配置`URL Types`里面填了一下`URL Schemes`这个内容，也没有其他业务代码
# 测试结果
- 安卓自带浏览器成功唤起了app
- ios狗带了，safari没有能成功唤起，而是重定向到了我这个页面的顶级域名去了……我这个页面是`https://abc.def.com/sth?id=1`这样的，它点击之后跳到了这个页面：`https://abc.def.com`，都没有打开那个失败的回调腾讯官网，但是它在safari中手动输入`a://`是能够唤端的，有个对话框，提示是否打开，点打开之后能成功打开app，我甚至单独写了个`div`，然后手动添加点击事件`window.location.href="a://"`，但是依旧是重定向到了我这个网页的顶级域名
# 其他
- 没了，求指点🤣🤣

**Comment by suanmei** [comment]
@SilentFlute 很明显不是 callapp-lib 的问题，你们的scheme不是约定了 host 为 `b` 吗，就说明scheme是 `a://b` ，在 ios 备忘录中写入 `a://b` ，此时它是可点击的，如果不能唤起 app ，锅就是 ios 开发同学的，如果可以，就应该排查重定向的问题出在哪儿，你可以在PC浏览器中输入你的 scheme 去排查。

只是给你解题思路，剩下的就要靠你自己了

**Comment by SilentFlute** [comment]
@suanmei 多谢多谢，果然是重定向的问题，那个`url scheme`的`scheme`字段和我们主站的域名有冲突，于是发生了重定向，修改之后就好了，安卓/ios自带浏览器均成功唤起了😘😘

**Comment by MissLixf** [comment]
您好，配置完成，并已安装公司应用，safari浏览器点击打开app,会先有弹框询问是否在应用中打开链接，等待1到2秒后点击 ‘是’ ，此时的行为是先唤起App(成功跳转到app), 然后又会马上跳转到App Store。这个怎么解决？

**Comment by SilentFlute** [comment]
@MissLixf 最近刚换了新的单位，暂时没有涉及该业务的场景，我依稀记得是如果点击之后x秒内没有响应，ios的话会唤起app store，就是判断结果为唤端失败了，然后打开app store，最后一次和这个作者大大讨论是ios要实现通用链接，安卓是app link吧我记得是，但后来app小伙伴有其他业务要做，我是把判断失败的超时时间直接改成了1天，这就避免了这个问题：点击打开app，无论等多久(1天以内)，再次点确定或者是，都能正常的走流程，你可以试试，以及还有一个问题：这个是否唤起成功的判断是页面隐藏，唤起了app或者app store都会触发页面隐藏，但是如果此时按home键，一样是页面隐藏，但却没有唤起app或者app store，这里需要注意，因为我上家公司流量比较小，因此也没有做特别的处理

**Comment by SilentFlute** [comment]
点击之后x秒内没有响应，ios的话会唤起app store的前提是你设置了ios中唤端失败的回调是唤起app store，看你这个情况，应该是设置了的，如果不是，但依旧唤起了app store，那你可能要好好排查下了
