### ISSUE TITLE
在一些安卓机的浏览器 点了没有反应

### ISSUE THREAD

**Issue by bensonwu97** [suanmei/callapp-lib#72]
+ 版本号: callapp-lib@

+ 配置Option: 

``` json
 {
  "scheme": {},
  "intent": {},
  "universal": {},
  "appstore": "",
  "yingyongbao": "",
  "fallback": ""
 }
```

+ 机型、系统、APP:小米自带浏览器

+ 遇到的问题及复现步骤:在一些安卓机的浏览器 点了没有反应

+ 期望的效果:

**Comment by githubmann** [comment]
同

**Comment by day-day-sleep** [comment]
小米 一加的手机都一样   走的都是chrome intent 存在app也能进行跳转  就是未安装app的时候  点击无效没有执行 chrome intent 的S.browser_fallback_url回调

**Comment by wangqilinqqq** [comment]
同问，我也遇到这个问题了

**Comment by chenxueling** [comment]
有解决吗这个问题

**Comment by kongling94** [comment]
同样 被国产浏览器恶心到了

**Comment by kongling94** [comment]
#61 补充一个问题，
二、一些安卓手机自带浏览器不能唤起app
原因：经反复测试之后发现，在手机自带浏览器内，某个网址第一次尝试打开app时，会有个是否打开某app的选择弹窗，浏览器会记住用户的选择。如用户选择「打开」，之后每次都不出现选择弹窗，每次直接跳转app；如果用户选择「取消」，之后该网站就再也不出现是否打开某app的选择弹窗，所以就调不起app，除非用户在设置内清除浏览器的数据。

暂时只在小米手机浏览器内发现这个问题，qq浏览器都好使，暂时没找到好的解决办法。

**Comment by ciloi** [comment]
荣耀自带浏览器，不能唤起app，清空浏览器也不行，以为是自己使用问题，下载demo之后发现，能够唤起，然后继续看是唤起失败之后跳转到优酷本身的下载页面，那个下载页面唤起的，可能直接跳转唤起会更好点

**Comment by suanmei** [comment]
@ciloi demo已更新，之前写的优酷的scheme有问题，已换知乎的

**Comment by suanmei** [comment]
有适配问题的全部列到这个 issue 中哈，谢谢各位 @bensonwu97 @githubmann @wangqilinqqq @ciloi

**Comment by 418055151** [comment]
版本号: callapp-lib@3.5.3

配置Option:

 {
        scheme: {
          protocol: “”,
          host: “”
        },
        intent: {
          package: “”,
          scheme: “”,
        },
        appstore: “”,
        timeout: 600000,
      }
机型 HUAWEI P20 Pro、系统 Android 10、浏览器:Firefox Browser 116.0 

遇到的问题及复现步骤:在一些安卓机的Firefox浏览器 点了没有反应 callback 方法未触发

期望的效果:
解决该浏览器适配问题

**Comment by ciloi** [comment]
您好，我已经收到信件，我会尽快处理的……祝快乐每一天。
