### ISSUE TITLE
iso较高版本，timeout超时候在确认打开，先唤醒app，紧接着就唤醒appstore

### ISSUE THREAD

**Issue by yslqq** [suanmei/callapp-lib#74]
+ 版本号: callapp-lib@

+ 配置Option: 
export function checkOpen(cb, timeout) {
  const visibilityChangeProperty = getVisibilityChangeProperty();
  const timer = setTimeout(() => {
    const hidden = isPageHidden();
    if (!hidden) {
      cb();
    }
  }, timeout);

  if (visibilityChangeProperty) {
    document.addEventListener(visibilityChangeProperty, () => {
      clearTimeout(timer);
    });

    return;
  }

  window.addEventListener('pagehide', () => {
    clearTimeout(timer);
  });
}

+ 机型、系统、APP:  ios比较高的版本，手里的12.4和13出现此类情况

+ 遇到的问题及复现步骤:  当safari弹出确认跳转提示时，等待超过timeout时间后再点击确认跳转，会成功唤醒app，但是紧接着就会唤醒appstore

+ 期望的效果: 超时后，成功唤醒app后不再唤醒appstore

**Comment by Nick-QI** [comment]
同样的问题.占位;

**Comment by acpplife** [comment]
同样的问题已解决。需要ios端配置universal link就可以解决这个问题了。
@yslqq @Nick-QI

**Comment by archerU** [comment]
配置了universal link 也会出现这个问题

**Comment by archerU** [comment]
另外我的timeout 超时时间设置 400ms ，非常快就超时了。会出现，唤起app，然后跳转到应用宝/appstore 的情况

**Comment by mailbaoer** [comment]
嗯，我也遇到这个问题了，我开始设置的超时时间是1s，也跳走了，后来改长了超时时间到5s，一切正常了

**Comment by yslqq** [comment]
你这样做连标都治不了啊，中间等待时间过长的时候依然会出现




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"baoer"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 晚上7:24
收件人:&nbsp;"suanmei/callapp-lib"<callapp-lib@noreply.github.com&gt;;
抄送:&nbsp;"挽霞漾斜阳"<2324902209@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [suanmei/callapp-lib] iso较高版本，timeout超时候在确认打开，先唤醒app，紧接着就唤醒appstore (#74)




嗯，我也遇到这个问题了，我开始设置的超时时间是1s，也跳走了，后来改长了超时时间到5s，一切正常了

**Comment by githubofwyh** [comment]
出现同样的问题，因为safari会自动出现弹窗，弹窗期间不影响定时器运行，只要是通过判断时间差来判断是否成功唤起app应该就会出现这个问题

**Comment by kongling94** [comment]
解决的bug：在 ios 12.3 版本之后，Safari 会有一个 bug，就是 URL Scheme 跟 download App 先后一起使用的话，会同时唤起 App 然后再进入 App store，体验极差。使用 universal link 可以完美解决这个问题。
