### ISSUE TITLE
能换起app，但有个bug，safari给的弹窗我如果按取消也会触发open里的callback函数，那我到底怎么判断用户是否成功唤起app，能成功唤起但按取消也会触发callback函数

### ISSUE THREAD

**Issue by YaFeng1844173476** [suanmei/callapp-lib#77]
+ 版本号: callapp-lib@

+ 配置Option: 

``` json
 {
  "scheme": {},
  "outChain": {},
  "intent": {},
  "universal": {},
  "appstore": "",
  "yingyongbao": "",
  "fallback": ""
 }
```

+ 机型、系统、APP:

+ 遇到的问题及复现步骤:

+ 期望的效果:

**Comment by YaFeng1844173476** [comment]
好像解决了，只能根据判断页面切换来达到需求目的，api文档里的callback并不能解决safari里的弹窗取消问题
document.addEventListener('visibilitychange', function () {
                if (document.visibilityState === 'visible') {
                    alert('success')
                }
            })

**Comment by alanuuu** [comment]
这个目前应该没办法解决，本身监听页面隐藏就是hack的方法
