### ISSUE TITLE
会弹出一个下载apple-app-site-association文件的提示，可以去掉么

### ISSUE THREAD

**Issue by yupeng2015** [suanmei/callapp-lib#78]
+ 版本号: callapp-lib@ 最新的

+ 配置Option: 

``` json
const option = {
		scheme:{
			protocol:'https',
		},
		appstore: 'https://android.myapp.com/myapp/detail.htm?apkName=com.power.xxxxxx&ADTAG=mobile',
		yingyongbao: '//a.app.qq.com/o/simple.jsp?pkgname=com.youku.shortvideo',
		fallback:'https://www.baidu.com',
    };
    const lib = new CallApp(option);
    const callButton = document.querySelector('#call-button');

    callButton.addEventListener('click', () => {
      lib.open({
        path: 'www.xxx.com/.well-known/apple-app-site-association?type=JOB&id=842434d585444a06824f73380a4e14ce&timestamp=1571706829612',
      });
    });
```

+ 机型、系统、APP: ios13

+ 遇到的问题及复现步骤:会弹出一个下载apple-app-site-association文件的提示，可以去掉么

+ 期望的效果:如何去掉这个下载提示

**Comment by suanmei** [comment]
你的用法本身就是错的，请和example保持一致。然后 apple-app-site-association 本身就是个文件，你是要唤端，访问这个文件做什么

**Comment by yupeng2015** [comment]
> 你的用法本身就是错的，请和example保持一致。然后 apple-app-site-association 本身就是个文件，你是要唤端，访问这个文件做什么

但是ios端给我的的通用链接（universalLink）就是要访问到这个文件，然后后面拼接参数，深度唤醒app中的某个页面，请问universalLink应该怎么使用，我看到官方也是提到要访问这个问题

**Comment by suanmei** [comment]
Universal Link 在这个域名下就可以，而不是去访问这个文件的地址然后拼参数，你让他们把url地址改一下就好了。弹窗和库是没有关系的，是你写的这个url的问题。

调试是应该让 ios 同学去修改

**Comment by yupeng2015** [comment]
> 官方说访问这个文件只是用来测试一下文件是否正常，你的app初次使用这个 Universal Link 的时候它会自动下载这个文件，而不是你主动去访问

但是ios端说通用链接就是这么用的，必须要访问这个链接，大佬 970852318这是我qq，恳请帮忙一下，我知道不应该耽误您时间，但是可能需要问ios相关问题，有偿，恳请帮忙
