### ISSUE TITLE
如果APP在后台运行的时候被唤起无法接受到param里的值【Android端】

### ISSUE THREAD

**Issue by prohack** [suanmei/callapp-lib#79]
能正常唤起 但是如果APP（Android端）已经是打开的状态则无法收到param里的值，请问大大有解决方法吗，谢谢啦

**Comment by fenglintianxia6** [comment]
一.楼主解决了么？
二.楼主如果没有解决的话，补充一下：是通过scheme唤醒之后的app，放到后台，二次通过scheme唤醒时，接受不到scheme协议

**Comment by suanmei** [comment]
这个需要和安卓同学联调哈，这是两边的协议通信问题，和库无关
