### ISSUE TITLE
android唤端成功不会唤起

### ISSUE THREAD

**Issue by minlx** [suanmei/callapp-lib#8]
您好，包升级到1.7.0以后，android唤起app，后台没有打开app的情况下，没有走open方法下的失败回调，唤起了但是不会跳转到app内    之前用1.6.6的版本唤端是可以的，现在1.6.6的版本唤端失败走open方法下的callback了，唤起不了
![20386345-293f-425a-933b-4bd99f79c478](https://user-images.githubusercontent.com/32285503/47986463-cfb45700-e117-11e8-85d5-984f87070acb.png)

升级之后变成了如果后台打开app的话才可以成功唤起，但是唤起的页面不是open方法下path路径指向的那个页面

**Comment by suanmei** [comment]
Android在哪儿打开的，是浏览器吗还是什么？浏览器的话是什么浏览器？

然后你的问题我不是很了解：  
1.6.6是一直就唤起失败，但是会执行你传入的callback

1.7.0是只有在预先打开app的情况下才能通过callapp-lib来唤端，但是如果唤端失败不会执行callback

我理解的对吗

**Comment by minlx** [comment]
> Android在哪儿打开的，是浏览器吗还是什么？浏览器的话是什么浏览器？
> 
> 然后你的问题我不是很了解：
> 1.6.6是一直就唤起失败，但是会执行你传入的callback
> 
> 1.7.0是只有在预先打开app的情况下才能通过callapp-lib来唤端，但是如果唤端失败不会执行callback
> 
> 我理解的对吗

**Comment by minlx** [comment]
> Android在哪儿打开的，是浏览器吗还是什么？浏览器的话是什么浏览器？
> 
> 然后你的问题我不是很了解：
> 1.6.6是一直就唤起失败，但是会执行你传入的callback
> 
> 1.7.0是只有在预先打开app的情况下才能通过callapp-lib来唤端，但是如果唤端失败不会执行callback
> 
> 我理解的对吗？
> 
> 我看你的path很奇怪。。。你可以把你的配置参数露出来，那个无关影响的，这些想抓都是能抓到的。

重复＃

**Comment by suanmei** [comment]
怎么就关掉了。。。。

**Comment by minlx** [comment]
> > Android在哪儿打开的，是浏览器吗还是什么？浏览器的话是什么浏览器？
> > 然后你的问题我不是很了解：
> > 1.6.6是一直就唤起失败，但是会执行你传入的callback
> > 1.7.0是只有在预先打开app的情况下才能通过callapp-lib来唤端，但是如果唤端失败不会执行callback
> > 我理解的对吗

不小心点错了。。。。

**Comment by minlx** [comment]
> > Android在哪儿打开的，是浏览器吗还是什么？浏览器的话是什么浏览器？
> > 然后你的问题我不是很了解：
> > 1.6.6是一直就唤起失败，但是会执行你传入的callback
> > 1.7.0是只有在预先打开app的情况下才能通过callapp-lib来唤端，但是如果唤端失败不会执行callback
> > 我理解的对吗

android是在手机自带浏览器里打开的  1.6.6之前用的时候是可以成功唤起的，最近优化代码发现唤起不了了，执行callback失败了  
1.7.0您理解的是对的的  那个path路径是app:8080/sdkment

**Comment by suanmei** [comment]
我现在在路上，晚上帮你看一下。

我最近准备把打包出来的文件移除压缩，方便你们自行 debug，你感觉怎么样

你的path一直没有换过吗，因为 scheme一般都是这个样子的

`${options.protocol}://${path}${urlQuery}`;

你这个又多出一个冒号，我没遇到过这种情况，不知道 app 能否识别

**Comment by minlx** [comment]
> path

好的，麻烦你啦，我的path没有换过，使用window.location.href app可能唤起  app:8080/sdkment 这个是open方法里传递的那个path参数

**Comment by suanmei** [comment]
你可以问一下Android同学需要的完整scheme是什么样的，然后对比一下看看

**Comment by minlx** [comment]
好的，我知道啦，

**Comment by minlx** [comment]
> @suanmei  android 唤端的时候 我把generateIntent 方法的return `intent://${urlPath}/${intentTail}`中的intent 换成 我司app的scheme去掉了intentTail 然后唤起成功了。。。。

**Comment by suanmei** [comment]
@minlx 那就是说你司的 scheme 唤端是 okay 的，intent 唤端不行。

那你们公司的 app Android 端支持 Intent 唤端吗

**Comment by minlx** [comment]
@suanmei  我刚才问了android的同学 scheme 可以更改成intent 但是现在他们是不支持的

**Comment by suanmei** [comment]
那你不应改去改动 generateIntent ，使用callapp-lib 的时候不传递 Intent 属性就好了

**Comment by minlx** [comment]
不传Intent的话 open 不会被执行啊，穿空字符串唤起失败  判断browser 的时候走到了 这个browser.isOriginalChrome判断里面，我再改改

**Comment by suanmei** [comment]
@minlx 这里还真是我记错了

有个地方你得小心，谷歌官方开发文档上明确说明，谷歌浏览器 25 以上版本不支持 Scheme ，你下载谷歌浏览器验证一下

**Comment by minlx** [comment]
嗯呢，我知道啦，我去试试
