### ISSUE TITLE
支付宝唤醒怎么配置

### ISSUE THREAD

**Issue by yetHandsome** [suanmei/callapp-lib#80]
+ 版本号: callapp-lib@
https://unpkg.com/callapp-lib@2.1.5/dist/index.umd.min.js
+ 配置Option: 
不知道

+ 机型、系统、APP:
苹果8 、谷歌浏览器
+ 遇到的问题及复现步骤:
想要用这个通过谷歌浏览器唤醒
alipays://platformapi/startapp?saId=10000007&qrcode=some_url
不知道怎么配置
+ 期望的效果:
点击后能唤醒支付宝
类似下面那个在苹果手机自动浏览器是可以的，但是谷歌浏览器就不行了
location.href=alipays://platformapi/startapp?saId=10000007&qrcode=some_url

我想应该很多人会想知道怎么唤醒支付宝，希望给给例子看看

**Comment by suanmei** [comment]
chrome浏览器可以通过模拟A标签点击，进行唤起。

你需要的 配置项：

``` 
const option = {
  scheme: {
    protocol: 'alipays'
  },
  ...
  ...
};

lib.open({
  path: 'platformapi/startapp',
  param: { saId: 10000007, qrcode: 'some_url' }
})
```
