### ISSUE TITLE
iOS 微信 版本大于 7.0.5 时，判断使用通用连接打开有Bug，版本比较Bug

### ISSUE THREAD

**Issue by mygongsun** [suanmei/callapp-lib#82]
+ 版本号: callapp-lib@2.1.8

+ 机型、系统、APP:

iOS 微信内 版本 >= 7.0.10

+ 遇到的问题及复现步骤:

iOS 微信 < 7.0.5版本不支持通用连接中版本判断有Bug，直接字符串比较，导致微信版本7.0.10 < 7.0.5 = true 不会换气App，直接跳转appstore设置的连接了 希望有时间能修复一下，我们现在是自己改了一下，下次再 npm i 包的时候不是很方便

**Comment by suanmei** [comment]
已修复
