### ISSUE TITLE
在唤起app的同时，也进行了下载app(进入fallback)怎么办？

### ISSUE THREAD

**Issue by phebe111** [suanmei/callapp-lib#83]
+ 版本号: callapp-lib@

+ 配置Option: 

``` json
 {
  "scheme": {},
  "outChain": {},
  "intent": {},
  "universal": {},
  "appstore": "",
  "yingyongbao": "",
  "fallback": ""
 }
```

+ 机型、系统、APP:

+ 遇到的问题及复现步骤:

+ 期望的效果:

**Comment by mzcc666GtHb** [comment]
这个问题解决了吗?

**Comment by githubofwyh** [comment]
同样遇到这个问题

**Comment by kongling94** [comment]
同样遇到。。

**Comment by theLongGoodbye** [comment]
同遇到这个问题，唤起了 app，但还是会触发失败回调，作者能看一下吗o(╥﹏╥)o

**Comment by soulcm** [comment]
同样遇到了，求解

**Comment by phebe111** [comment]
这个问题没有解决。后面我没有用callapp-lib方法了，希望解决的朋友们可以分享一下方法
我改用的方法：用安卓scheme(安卓同事提供打开app的协议)来调起app,先判断是否安装，启动间隔20ms运行的定时器，并检测累计消耗时间是否超过3000ms，超过则结束

**Comment by phebe111** [comment]
> 同遇到这个问题，唤起了 app，但还是会触发失败回调，作者能看一下吗o(╥﹏╥)o

没有解决。我改用的方法：用安卓scheme(安卓同事提供打开app的协议)来调起app,先判断是否安装，启动间隔20ms运行的定时器，并检测累计消耗时间是否超过3000ms，超过则结束

**Comment by phebe111** [comment]
> 同样遇到了，求解

没有解决。我改用的方法：用安卓scheme(安卓同事提供打开app的协议)来调起app,先判断是否安装，启动间隔20ms运行的定时器，并检测累计消耗时间是否超过3000ms，超过则结束

**Comment by phebe111** [comment]
> 这个问题解决了吗?

没有解决。我改用的方法：用安卓scheme(安卓同事提供打开app的协议)来调起app,先判断是否安装，启动间隔20ms运行的定时器，并检测累计消耗时间是否超过3000ms，超过则结束

**Comment by suanmei** [comment]
> > 这个问题解决了吗?
> 
> 没有解决。我改用的方法：用安卓scheme(安卓同事提供打开app的协议)来调起app,先判断是否安装，启动间隔20ms运行的定时器，并检测累计消耗时间是否超过3000ms，超过则结束

这样可以解决 进入 fallback 的问题吗，和直接 setTimeout(callback, 3000)的区别是什么

**Comment by githubofwyh** [comment]
> > 这个问题解决了吗?
> 
> 没有解决。我改用的方法：用安卓scheme(安卓同事提供打开app的协议)来调起app,先判断是否安装，启动间隔20ms运行的定时器，并检测累计消耗时间是否超过3000ms，超过则结束

我参考了知乎、网易他们分享h5并唤起app的流程，发现只用url scheme没办法完美解决，ios需要用Universal Links。因为Universal Links本身就是一个https链接，当安装过app，可以跳转app；如果没安装，这个链接会被当作正常的https链接访问，此时在该域名下配置一个下载页面即可。

**Comment by alanuuu** [comment]
我后面是用的魔链，不知道他们怎么处理的

**Comment by tianwen20** [comment]
这个库的原理是，按照options的timeout，来设置一个timeout，然后监听页面的visibilityChange或者pagehide事件，如果监听到了就会清除timeout，你们的打开了app并且打开了appstore，是因为设置的timeout时间太短，设置的稍微长一些，会避免大多数情况下出现该问题，比如3000ms，但是会出现app不存在，会很久才自动跳转下载链接

**Comment by suanmei** [comment]
> 这个库的原理是，按照options的timeout，来设置一个timeout，然后监听页面的visibilityChange或者pagehide事件，如果监听到了就会清除timeout，你们的打开了app并且打开了appstore，是因为设置的timeout时间太短，设置的稍微长一些，会避免大多数情况下出现该问题，比如3000ms，但是会出现app不存在，会很久才自动跳转下载链接

正解！需要自己取舍。可以参照知乎，500ms左右，不管你有没有都会跳转下载页
