### ISSUE TITLE
在微信中唤起淘宝app可以实现吗

### ISSUE THREAD

**Issue by sjh0824** [suanmei/callapp-lib#84]
+ 版本号: callapp-lib@

+ 配置Option: 
  const option = {
        scheme: {
            protocol: 'taobao://',
        },
        // universal: {
        //     host: 'flash-link.youku.com',
        //     pathKey: 'action',
        // },
        appstore: 'https://apps.apple.com/cn/app/%E6%89%8B%E6%9C%BA%E6%B7%98%E5%AE%9D-%E6%B7%98%E5%88%B0%E4%BD%A0%E8%AF%B4%E5%A5%BD/id387682726',
        // appstore: 'https://appgallery.cloud.huawei.com/uowap/index.html#/detailApp/C34075?subsource=C34075&shareFrom=appmarket&shareTo=weixin&source=appshare&locale=zh_CN',
        yingyongbao: 'https://m.pp.cn/detail.html?query=%E6%B7%98%E5%AE%9D&ch=smbox&ch_src=sm&appid=32267',
        fallback: 'https://m.pp.cn/detail.html?query=%E6%B7%98%E5%AE%9D&ch=smbox&ch_src=sm&appid=32267',
        timeout: 2000,
    };
    const lib = new CallApp(option);
    const callButton = document.querySelector('#call-button');

    callButton.addEventListener('click', () => {
        lib.open({
            path: 'taobao://detail.tmall.com/item.htm?spm=a1z10.1-b-s.w5003-22314844004.2.68047a58A5zVLq&id=531622993372&scene=taobao_shop',
        });
    });

+ 机型、系统、APP:
    苹果和安卓
+ 遇到的问题及复现步骤:
    在微信中需要唤起淘宝app，但是配置好了，点击之后，没有唤起app，这是怎么回事，是不是配置的问题，还是说在微信内不支持唤起淘宝app?
+ 期望的效果:
   在微信中需要唤起淘宝app，这个可以实现吗

**Comment by suanmei** [comment]
微信不支持scheme唤端，而且微信也不会允许唤起淘宝
