### ISSUE TITLE
iOS检测是否安装APP不成功

### ISSUE THREAD

**Issue by cueker** [suanmei/callapp-lib#86]
+ 版本号: callapp-lib@2.1.8

+ 配置Option: 
``` json
{
	"scheme": {
		"protocol": "jccyapp",
		"host": "app.jccyapp.com",
		"port": ""
	},

	"intent": {
		"package": "com.jccy",
		"scheme": "jccyapp"
	},

	"universal": {
		"host": "app.jccyapp.com",
		"pathKey": "path"
	},

	"appstore": "https://apps.apple.com/cn/app/%E8%81%9A%E5%BD%A9%E6%88%90%E5%A3%B9/id1488287781",
	"fallback": "http://cdn.jccyapp.com/package/latest.apk",
	"timeout": 1000
}
```

+ 机型、系统、APP:
iphone8P、iOS12.4.1、聚彩APP 

+ 遇到的问题及复现步骤:

在手机safari中打开 [该链接](https://cdn.jccyapp.com/package/index.html) ，点击下载，未安装APP，没有跳转到AppStore

+ 期望的效果:
点击下载------>检测是否安装APP-------是--->打开APP
                                                      |
                                                      |------否---->去AppStore下载

**Comment by uncleMrWang** [comment]
请问解决了么。，，我也是遇到这个问题了

**Comment by cueker** [comment]
我让后台做了302跳到苹果商店了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "uncleMrWang"<notifications@github.com&gt;; 
发送时间: 2020年3月28日(星期六) 上午9:36
收件人: "suanmei/callapp-lib"<callapp-lib@noreply.github.com&gt;; 
抄送: "李明"<379454125@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [suanmei/callapp-lib] iOS检测是否安装APP不成功 (#86)





 
请问解决了么。，，我也是遇到这个问题了

**Comment by suanmei** [comment]
不是很明白，很奇怪，文案也不对。文案应该是 `打开app` 或者  `在app中打开`，`点击下载`是你确定让用户去下载。
然后再说你的逻辑，你如果在ios中想看某个app是否安装，你就正常使用universalLink，有app它就会帮你唤起，没有的话就会跳转到这个地址对应的页面，当然你可以nginx配置它指向任意地址。

**Comment by yanhongchang-1105** [comment]
那 appstore 地址没什么用了呢
