### ISSUE TITLE
ios 和安卓的scheme 不一致

### ISSUE THREAD

**Issue by Lyan0505** [suanmei/callapp-lib#88]
+ 版本号: callapp-lib@

+ 配置Option: 

``` json
 {
  "scheme": {},
  "outChain": {},
  "intent": {},
  "universal": {},
  "appstore": "",
  "yingyongbao": "",
  "fallback": ""
 }
```

+ 机型、系统、APP:

+ 遇到的问题及复现步骤:

+ 期望的效果:

**Comment by Lyan0505** [comment]
如果客户端 安卓和ios 的唤起吗不一样呢？ 怎么配置

**Comment by hasbug** [comment]
> 如果客户端 安卓和ios 的唤起吗不一样呢？ 怎么配置

是自己的APP吗？ 要求一致呗

**Comment by suanmei** [comment]
自家app，跟客户端同学提需求，保持一致，包括唤起app之后的行为所对应的scheme都需要一致，不然同样需求，你配置两份，不合理
