### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by uncleMrWang** [suanmei/callapp-lib#89]
+ 版本号: callapp-lib@
2.1.8
+ 配置Option: 

``` json
scheme: {
							protocol: 'matrixrecycle',
						},
						intent: {
							package: 'com.matrixrecycle.no1',
							scheme: 'matrixrecycle',
						},
						universal: {
							host: 'www.matrixrecycle.com/ulink/',
							pathKey: 'action',
						},
						appstore: 'https://apps.apple.com/cn/app/%E6%A0%BC%E5%AD%90%E5%9B%9E%E6%94%B6/id1483199279',
						yingyongbao: '',
						fallback: ‘https://api.matrixrecycle.com/api/file/nottoken/app/download/com.matrixrecycle.no1’,
						timeout: 3000,
```

+ 机型、系统、APP:
iphone7 13.3  
+ 遇到的问题及复现步骤:
自带的safari使用通用链接  未安装app的情况下跳转404  。。安装了的情况下可以打开app
+ 期望的效果:
![image](https://user-images.githubusercontent.com/26252498/77757729-b5607d80-706c-11ea-92ce-fbbe9f57887d.png)
请问下这个是我服务器配置的异常么

**Comment by suanmei** [comment]
是这样子，你需要nginx配置你的universal-link地址对应一个页面，用来做app不存在时候的展示，例:   https://oia.zhihu.com/question/270839820/answer/477722658
