### ISSUE TITLE
在安卓手机百度浏览器跳转错误，generateIntent方法有误

### ISSUE THREAD

**Issue by beicheng112** [suanmei/callapp-lib#9]
` return  intent://${urlPath}/${intentTail};
应改为 
return  intent://${urlPath}${intentTail}`

**Comment by suanmei** [comment]
generateIntent 已去除 `/` 

安卓手百问题在文章里有提到，手百对 scheme 进行了拦截，和微信同理，如果需要通过安卓手百唤端，需要联系手百添加白名单。ios 手百目前没有对 unviersalLink 封锁，唤端功能正常
