### ISSUE TITLE
没适配新的ios ua规则，isIos无法判断ios13 以上的iPad

### ISSUE THREAD

**Issue by Josh-zx** [suanmei/callapp-lib#97]

**Comment by suanmei** [comment]
哪里无法判断呢

**Comment by Josh-zx** [comment]
> 哪里无法判断呢

我看现在判断ios环境是这样的
`export const isIos = /iphone|ipad|ipod/i.test(ua);`
但ios13开始，iPad的ua里已经没有ipad关键字了

**Comment by suanmei** [comment]
> 
> 我看现在判断ios环境是这样的
> `export const isIos = /iphone|ipad|ipod/i.test(ua);`
> 但ios13开始，iPad的ua里已经没有ipad关键字了
但是我用safari或者一些app测试，目前都是包含ipad的。你那边如果没有，方便发个截图吗

**Comment by Josh-zx** [comment]
> 我看现在判断ios环境是这样的
> `export const isIos = /iphone|ipad|ipod/i.test(ua);`
> 但ios13开始，iPad的ua里已经没有ipad关键字了
> 但是我用safari或者一些app测试，目前都是包含ipad的。你那边如果没有，方便发个截图吗

**Comment by Josh-zx** [comment]
> 我看现在判断ios环境是这样的
> `export const isIos = /iphone|ipad|ipod/i.test(ua);`
> 但ios13开始，iPad的ua里已经没有ipad关键字了
> 但是我用safari或者一些app测试，目前都是包含ipad的。你那边如果没有，方便发个截图吗

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15"
这个是我找了个ipad拿出来的，13的系统
